//! rust-allocator — forge lab 01.
//!
//! Build a real free-list allocator over a fixed heap: split, coalesce,
//! respect alignment, reuse freed blocks. This is the same design problem as
//! vLLM's KV-cache block manager — fixed-size backing store, adversarial
//! sizes, fragmentation as the failure mode (lesson T1.L6, then T5.L5).
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/allocator.rs   (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The checks below are the single source of truth:
//!   * `cargo test` runs them on your machine.
//!   * `cargo build --release --target wasm32-unknown-unknown` bakes them
//!     into the .wasm you drop into kernelspace → the site calls `ks_run`
//!     and renders exactly these results.
//!
//! A `todo!()` in your code traps the wasm module; the site shows that as
//! "not implemented yet". Finish all six checks to complete the lab.

mod allocator;

use allocator::Allocator;
use kslab::{Check, Report};

const CAP: usize = 1 << 20; // 1 MiB simulated heap

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — a seeded PRNG so the browser and `cargo test` see the
/// exact same trace every time. No `rand` dependency.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    /// 0..n
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. boot: the allocator constructs and hands out its first byte.
pub fn check_boot() -> Check {
    const ID: &str = "boot";
    const LABEL: &str = "constructs and serves a first allocation";
    let mut a = Allocator::new(CAP);
    match a.alloc(1, 1) {
        Some(_) => Check::pass(ID, LABEL, "allocator is alive"),
        None => Check::fail(ID, LABEL, "alloc(1, 1) on an empty 1 MiB heap returned None"),
    }
}

/// 2. align: every returned offset satisfies the requested alignment.
pub fn check_align() -> Check {
    const ID: &str = "align";
    const LABEL: &str = "returned offsets respect alignment (1–256)";
    let aligns = [1usize, 2, 4, 8, 16, 32, 64, 128, 256];
    let mut a = Allocator::new(CAP);
    let mut rng = Rng(0xA11C);
    let mut live: Vec<(usize, usize)> = Vec::new();
    for i in 0..200 {
        let al = aligns[rng.below(aligns.len())];
        let sz = 1 + rng.below(512);
        match a.alloc(sz, al) {
            Some(p) => {
                if p % al != 0 {
                    return Check::fail(
                        ID,
                        LABEL,
                        format!("op {i}: alloc({sz}, align {al}) returned {p} — not {al}-aligned"),
                    );
                }
                live.push((p, sz));
                // keep live usage tiny (≤ 64 × 512 B) so None is always a bug
                if live.len() > 64 {
                    let (p, s) = live.remove(0);
                    a.free(p, s);
                }
            }
            None => {
                return Check::fail(
                    ID,
                    LABEL,
                    format!("op {i}: alloc({sz}, {al}) failed with <64 KiB live — heap is 1 MiB"),
                )
            }
        }
    }
    Check::pass(ID, LABEL, "200/200 allocations correctly aligned")
}

/// 3. no-overlap: no two live allocations ever share a byte.
pub fn check_no_overlap() -> Check {
    const ID: &str = "no_overlap";
    const LABEL: &str = "live allocations never overlap";
    let mut a = Allocator::new(CAP);
    let mut rng = Rng(0xB0B);
    let mut live: Vec<(usize, usize)> = Vec::new();
    for i in 0..400 {
        let do_alloc = live.is_empty() || rng.below(100) < 60;
        if do_alloc {
            let sz = 8 + rng.below(1016);
            let al = 1usize << rng.below(7); // 1..64
            match a.alloc(sz, al) {
                Some(p) => {
                    for &(lp, ls) in &live {
                        if p < lp + ls && lp < p + sz {
                            return Check::fail(
                                ID,
                                LABEL,
                                format!(
                                    "op {i}: [{p}, {}) overlaps live [{lp}, {})",
                                    p + sz,
                                    lp + ls
                                ),
                            );
                        }
                    }
                    live.push((p, sz));
                }
                None => {
                    return Check::fail(
                        ID,
                        LABEL,
                        format!("op {i}: alloc({sz}, {al}) failed with {} bytes live", live.iter().map(|&(_, s)| s).sum::<usize>()),
                    )
                }
            }
        } else {
            let idx = rng.below(live.len());
            let (p, s) = live.remove(idx);
            a.free(p, s);
        }
    }
    Check::pass(ID, LABEL, "400 mixed ops, zero overlaps")
}

/// 4. coalesce: 16 freed 4 KiB blocks must merge back into one 64 KiB run.
pub fn check_coalesce() -> Check {
    const ID: &str = "coalesce";
    const LABEL: &str = "adjacent free blocks coalesce";
    let mut a = Allocator::new(CAP);
    let mut ptrs = Vec::new();
    for _ in 0..16 {
        match a.alloc(4096, 16) {
            Some(p) => ptrs.push(p),
            None => {
                return Check::fail(ID, LABEL, "could not place 16 × 4 KiB on a 1 MiB heap")
            }
        }
    }
    for p in ptrs {
        a.free(p, 4096);
    }
    match a.alloc(1 << 16, 16) {
        Some(_) => Check::pass(ID, LABEL, "64 KiB allocation succeeded after freeing 16 × 4 KiB"),
        None => Check::fail(
            ID,
            LABEL,
            "64 KiB allocation failed after freeing 16 adjacent 4 KiB blocks — free() must coalesce neighbors",
        ),
    }
}

/// 5. reuse: a freed block is handed out again (bump allocators fail here).
pub fn check_reuse() -> Check {
    const ID: &str = "reuse";
    const LABEL: &str = "freed blocks are reused";
    let mut a = Allocator::new(CAP);
    let p1 = match a.alloc(1024, 8) {
        Some(p) => p,
        None => return Check::fail(ID, LABEL, "first alloc failed"),
    };
    a.free(p1, 1024);
    match a.alloc(1024, 8) {
        Some(p2) if p2 == p1 => Check::pass(ID, LABEL, "freed block served the next same-size alloc"),
        Some(p2) => Check::fail(
            ID,
            LABEL,
            format!("freed block at {p1} ignored; next 1 KiB alloc landed at {p2} — bump-only growth?"),
        ),
        None => Check::fail(ID, LABEL, "alloc after free returned None"),
    }
}

/// 6. fragmentation: ~45 % occupancy churn for 3000 ops must never fail.
///    Bump and non-coalescing allocators die here; first-fit + coalesce
///    (and pow2 size-class designs) pass comfortably.
pub fn check_fragmentation() -> Check {
    const ID: &str = "fragmentation";
    const LABEL: &str = "3000-op churn at ~45% occupancy: zero failures";
    let mut a = Allocator::new(CAP);
    let mut rng = Rng(0xF7A6);
    let mut live: Vec<(usize, usize)> = Vec::new();
    let mut live_bytes = 0usize;
    let mut peak = 0usize;
    let target = CAP * 45 / 100;
    for i in 0..3000 {
        if live_bytes < target {
            let sz = 64 + rng.below(1985); // 64..2048
            match a.alloc(sz, 8) {
                Some(p) => {
                    live.push((p, sz));
                    live_bytes += sz;
                    peak = peak.max(live_bytes);
                }
                None => {
                    return Check::fail(
                        ID,
                        LABEL,
                        format!(
                            "op {i}: alloc({sz}) failed with {} KiB live / 1024 KiB — fragmentation (peak {} KiB)",
                            live_bytes / 1024,
                            peak / 1024
                        ),
                    )
                }
            }
        } else {
            let idx = rng.below(live.len());
            let (p, s) = live.remove(idx);
            a.free(p, s);
            live_bytes -= s;
        }
    }
    Check::pass(
        ID,
        LABEL,
        format!("3000 ops survived; peak live {} KiB of 1024 KiB", peak / 1024),
    )
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_boot(),
        check_align(),
        check_no_overlap(),
        check_coalesce(),
        check_reuse(),
        check_fragmentation(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "rust-allocator", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
