//! mpmc-queue — forge lab 04.
//!
//! The intake ring of every serving engine: bounded, multi-producer,
//! multi-consumer, no locks. You are building Dmitry Vyukov's MPMC queue —
//! per-slot sequence numbers, two cursors, CAS — the same shape as
//! io_uring's submission ring and the queue between a router and a
//! scheduler. T2.L5 showed you the picture; here you make it correct.
//!
//! ┌─────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/queue.rs       (the only file with TODO(you))  │
//! │  DO NOT EDIT this file — it is the grading harness.             │
//! └─────────────────────────────────────────────────────────────────┘
//!
//! The contract:
//!   * `new(capacity)` — a bounded ring with `capacity` usable slots.
//!     (Checks only use power-of-two capacities; rounding up internally
//!     is your business.)
//!   * `push(v)`  — `Ok(())` if a slot was free, `Err(v)` — handing the
//!     value BACK — if full. That Err is backpressure: the caller keeps
//!     the request and retries or sheds. Never block, never drop.
//!   * `pop()`    — `Some(v)` in FIFO order, `None` if empty.
//!   * Methods take `&self`: the queue is shared across threads. Your
//!     interior state synchronizes itself (atomics). No Mutex — that is
//!     the entire point of the lab.
//!
//! Why the checks look like this: in a single-threaded wasm sandbox we
//! cannot create real races — so the six checks are *semantic*: FIFO,
//! backpressure, wraparound, and 5000 shadowed ops against a model
//! (every race bug starts life as a logic bug). The REAL race fuzzer is
//! native-only: `cargo test` also runs `stress_threads` — 4 producers,
//! 4 consumers, 100k items, conservation checked — which compiles only
//! for your host target. Both suites must pass.

mod queue;

pub use queue::Queue;
use kslab::{Check, Report};

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. fifo: order is the contract.
pub fn check_fifo() -> Check {
    const ID: &str = "fifo";
    const LABEL: &str = "strict FIFO order";
    let q = Queue::new(8);
    for v in 1..=8u64 {
        if q.push(v).is_err() {
            return Check::fail(ID, LABEL, format!("push({v}) failed into an 8-slot ring after {} pushes", v - 1));
        }
    }
    for want in 1..=8u64 {
        match q.pop() {
            Some(got) if got == want => {}
            other => return Check::fail(ID, LABEL, format!("pop = {other:?}, want Some({want})")),
        }
    }
    if q.pop().is_some() {
        return Check::fail(ID, LABEL, "pop on a drained ring must be None");
    }
    Check::pass(ID, LABEL, "8 in, 8 out, exact order, empty says None")
}

/// 2. backpressure: a full ring hands the value back; space recycles.
pub fn check_backpressure() -> Check {
    const ID: &str = "backpressure";
    const LABEL: &str = "full ring returns Err(v); freed slots recycle";
    let q = Queue::new(4);
    for v in 10..14u64 {
        if q.push(v).is_err() {
            return Check::fail(ID, LABEL, format!("push({v}) failed before the ring was full"));
        }
    }
    match q.push(99) {
        Err(99) => {}
        Err(v) => return Check::fail(ID, LABEL, format!("full ring returned Err({v}) — the caller's value was swapped")),
        Ok(()) => return Check::fail(ID, LABEL, "5th push into a 4-slot ring succeeded — slot from nowhere"),
    }
    if q.pop() != Some(10) {
        return Check::fail(ID, LABEL, "pop after overflow lost the head value");
    }
    if q.push(99).is_err() {
        return Check::fail(ID, LABEL, "push after pop failed — freed slot was not recycled");
    }
    Check::pass(ID, LABEL, "overflow is honest, recycling works")
}

/// 3. wraparound: cursors cycle forever; the ring never "fills up" over time.
pub fn check_wraparound() -> Check {
    const ID: &str = "wraparound";
    const LABEL: &str = "1000 cycles through a 4-slot ring";
    let q = Queue::new(4);
    let mut next_in = 0u64;
    let mut next_out = 0u64;
    for cycle in 0..1000 {
        for _ in 0..4 {
            next_in += 1;
            if q.push(next_in).is_err() {
                return Check::fail(ID, LABEL, format!("cycle {cycle}: push({next_in}) failed — cursors stuck?"));
            }
        }
        for _ in 0..4 {
            next_out += 1;
            match q.pop() {
                Some(v) if v == next_out => {}
                other => return Check::fail(ID, LABEL, format!("cycle {cycle}: pop = {other:?}, want Some({next_out})")),
            }
        }
    }
    Check::pass(ID, LABEL, "4000 ops, order intact after 1000 full wraps")
}

/// 4. model_gauntlet: 3000 random ops shadowed by a VecDeque — every
///    Ok/Err decision and every value must match the model exactly.
pub fn check_model_gauntlet() -> Check {
    const ID: &str = "model_gauntlet";
    const LABEL: &str = "3000 random ops vs a reference model";
    let q = Queue::new(8);
    let mut model: std::collections::VecDeque<u64> = Default::default();
    let mut rng = Rng(0x44C4);
    for op in 0..3000 {
        if rng.below(100) < 55 {
            let v = rng.next();
            let want = model.len() < 8;
            match (q.push(v), want) {
                (Ok(()), true) => {
                    model.push_back(v);
                }
                (Err(e), false) => {
                    if e != v {
                        return Check::fail(ID, LABEL, format!("op {op}: Err({e}) returned a different value than pushed ({v})"));
                    }
                }
                (Ok(()), false) => return Check::fail(ID, LABEL, format!("op {op}: push succeeded with a full ring (model has 8)")),
                (Err(_), true) => return Check::fail(ID, LABEL, format!("op {op}: push failed with {} items in the model", model.len())),
            }
        } else {
            let want = model.pop_front();
            if q.pop() != want {
                return Check::fail(ID, LABEL, format!("op {op}: pop disagreed with model (want {want:?})"));
            }
        }
    }
    Check::pass(ID, LABEL, "3000/3000 decisions match the model")
}

/// 5. slot_conservation: fill → drain → refill, 100 times. A ring that
///    loses a slot per cycle dies here.
pub fn check_slot_conservation() -> Check {
    const ID: &str = "slot_conservation";
    const LABEL: &str = "fill/drain × 100: every slot returns every time";
    let q = Queue::new(16);
    for cycle in 0..100 {
        for v in 0..16u64 {
            if q.push(v).is_err() {
                return Check::fail(ID, LABEL, format!("cycle {cycle}: slot {v} unavailable — the ring is leaking slots"));
            }
        }
        for _ in 0..16 {
            if q.pop().is_none() {
                return Check::fail(ID, LABEL, format!("cycle {cycle}: ring dried up early"));
            }
        }
    }
    Check::pass(ID, LABEL, "1600 ops, 16 slots, zero leaks")
}

/// 6. burst_model: serving traffic is bursty — floods then dry spells,
///    shadowed by the model.
pub fn check_burst_model() -> Check {
    const ID: &str = "burst_model";
    const LABEL: &str = "bursty traffic vs the model (2000 ops)";
    let q = Queue::new(16);
    let mut model: std::collections::VecDeque<u64> = Default::default();
    let mut rng = Rng(0xB47);
    let mut ops = 0usize;
    while ops < 2000 {
        // a burst of 1..24 pushes
        for _ in 0..(1 + rng.below(24)) {
            let v = rng.next();
            match (q.push(v), model.len() < 16) {
                (Ok(()), true) => model.push_back(v),
                (Err(e), false) => {
                    if e != v {
                        return Check::fail(ID, LABEL, format!("op {ops}: Err returned the wrong value"));
                    }
                }
                (Ok(()), false) => return Check::fail(ID, LABEL, format!("op {ops}: phantom slot")),
                (Err(_), true) => return Check::fail(ID, LABEL, format!("op {ops}: false full at {} items", model.len())),
            }
            ops += 1;
        }
        // drain 0..half
        for _ in 0..rng.below(9) {
            let want = model.pop_front();
            if q.pop() != want {
                return Check::fail(ID, LABEL, format!("op {ops}: pop disagreed with model"));
            }
            ops += 1;
        }
    }
    Check::pass(ID, LABEL, "bursts absorbed, every decision matched")
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_fifo(),
        check_backpressure(),
        check_wraparound(),
        check_model_gauntlet(),
        check_slot_conservation(),
        check_burst_model(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "mpmc-queue", version: 1, checks: self_checks() };
    kslab::emit(&report)
}

/* --------------------------- fleet bridge --------------------------- */
/* The Fleet (/fleet, engine mode) uses YOUR queue as the engine's intake
   ring — the backpressure valve between the router and the scheduler:

     init <capacity>     → ok
     push <v>            → ok | full      (full = shed the request)
     pop                 → <v> | empty
*/

use std::cell::RefCell;

thread_local! {
    static FLEET_QUEUE: RefCell<Option<Queue>> = const { RefCell::new(None) };
}

#[no_mangle]
pub extern "C" fn ks_invoke(in_ptr: u32, in_len: u32) -> u64 {
    let bytes = unsafe { std::slice::from_raw_parts(in_ptr as *const u8, in_len as usize) };
    let cmd = String::from_utf8_lossy(bytes).into_owned();
    let reply = FLEET_QUEUE.with(|q| dispatch(&mut q.borrow_mut(), cmd.trim()));
    kslab::emit_str(&reply)
}

fn dispatch(q: &mut Option<Queue>, cmd: &str) -> String {
    let mut parts = cmd.split_whitespace();
    match parts.next() {
        Some("init") => match parts.next().and_then(|s| s.parse::<usize>().ok()) {
            Some(cap) if cap > 0 => {
                *q = Some(Queue::new(cap));
                "ok".into()
            }
            _ => format!("err bad init '{cmd}'"),
        },
        Some("push") => {
            let Some(queue) = q.as_mut() else { return "err not initialized".into() };
            match parts.next().and_then(|s| s.parse::<u64>().ok()) {
                Some(v) => match queue.push(v) {
                    Ok(()) => "ok".into(),
                    Err(_) => "full".into(),
                },
                None => format!("err bad args '{cmd}'"),
            }
        }
        Some("pop") => {
            let Some(queue) = q.as_mut() else { return "err not initialized".into() };
            match queue.pop() {
                Some(v) => v.to_string(),
                None => "empty".into(),
            }
        }
        _ => "err unknown command".into(),
    }
}
