//! batching-scheduler — forge lab 06.
//!
//! The admission valve of the engine: who runs, who waits, who gets preempted.
//! You are graded on what the industry grades on — GOODPUT UNDER SLO —
//! across synthetic overloads and licensed production-shape replays. T5.L7,
//! with your hands on
//! the admission valve.
//!
//! ┌─────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/scheduler.rs   (the only file with TODO(you))  │
//! │  DO NOT EDIT this file — it is the simulator AND the harness.   │
//! └─────────────────────────────────────────────────────────────────┘
//!
//! The engine model (deliberately small, deliberately vLLM-shaped):
//!   * Time is discrete iterations (~50 ms each — one decode step).
//!   * A request is admitted → prefills (prompt_tokens / 128 iters) →
//!     decodes one token per iteration until its (hidden) output length.
//!   * You do NOT see output lengths. Production doesn't either.
//!   * Constraints: running ≤ max_running; resident memory = Σ (prompt
//!     + decoded) ≤ mem_cap. Memory is reserved for the whole prompt at
//!     admission — you pay for the context up front.
//!   * Every iteration you return an Action: who to admit from waiting,
//!     who to preempt back (their progress is DISCARDED — recompute
//!     preemption, vLLM-style).
//!   * ILLEGAL actions (admitting non-waiting ids, blowing a constraint)
//!     fail the scenario outright. All-or-nothing, like lab 02 taught.
//!   * SLO: TTFT = iterations from arrival to first token; a request
//!     meets the SLO iff it completes with TTFT ≤ the scenario's bound.
//!     Goodput = met / total. Raw throughput is not the metric.
//!
//! Template v2: every check runs on its own, in a fresh copy of your module,
//! and a `todo!()` traps only the checks that reach it. Four checks draw
//! their traffic from the seed (`runs_clean`, `slo_light`, `starvation`,
//! `overload_seeded`); `cargo test` runs them on their default seeds and on
//! 32 extra seeds. The scenarios with calibrated tables stay fixed: `burst`,
//! `convoy`, and `goodput_score`, whose three replay traces have floors
//! measured against the exact tables in the crate.
//!
//! Which check catches which mistake:
//!
//! ```text
//!   runs_clean       an illegal action, or a policy that stalls on light load
//!   slo_light        admitting so slowly that light traffic misses its TTFT
//!   burst            a batch that never fills: one request admitted at a time
//!   convoy           first-come-first-served: the whale goes first
//!   starvation       pure smallest-first: the three longs never run
//!   goodput_score    the replay traces (BurstGPT, LMSYS shape, one overload)
//!   overload_seeded  first-come-first-served on a freshly drawn overload
//!                    (optional): 400 requests at 2.4x, redrawn every run,
//!                    where `goodput_score` replays one fixed trace
//! ```

mod scheduler;
mod trace_scenarios;

use kslab::{Check, CheckDef, Ctx, Lab, Rng as SeedRng};
use scheduler::Scheduler;

pub const CHUNK: u32 = 128; // prefill tokens per iteration

/* --------------------------- public types --------------------------- */

pub struct ReqView {
    pub id: u32,
    pub arrival: u32,
    pub prompt_tokens: u32,
}

pub struct RunView {
    pub id: u32,
    pub arrival: u32,
    pub prompt_tokens: u32,
    pub decoded: u32,
    pub prefill_left: u32,
}

pub struct State<'a> {
    pub iter: u32,
    pub max_running: usize,
    pub mem_cap: u32,
    pub waiting: &'a [ReqView],
    pub running: &'a [RunView],
}

pub struct Action {
    pub admit: Vec<u32>,
    pub preempt: Vec<u32>,
}

/* ----------------------------- simulator ---------------------------- */
/* Everything below is pub so you can build your own baselines
(examples/ or tests/) and race them against your policy on the same
deterministic scenarios. The graded checks call exactly these. */

pub struct ReqSpec {
    pub id: u32,
    pub arrival: u32,
    pub prompt: u32,
    pub output: u32,
}

pub struct Scenario {
    pub name: &'static str,
    pub reqs: Vec<ReqSpec>,
    pub max_running: usize,
    pub mem_cap: u32,
    pub slo_ttft: u32,
    pub iters: u32,
}

#[derive(Default, Clone)]
pub struct Stats {
    pub total: usize,
    pub completed: usize,
    pub slo_met: usize,
    pub ttft_p95: u32,
    pub last_finish: u32,
    pub completed_ids: Vec<u32>,
}

struct Seq {
    spec: ReqSpec,
    prefill_left: u32,
    decoded: u32,
    ttft: Option<u32>,
}

fn percentile95(mut xs: Vec<u32>) -> u32 {
    if xs.is_empty() {
        return 0;
    }
    xs.sort_unstable();
    xs[((xs.len() as f64) * 0.95).ceil() as usize - 1]
}

impl Stats {
    pub fn goodput(&self) -> f64 {
        self.slo_met as f64 / self.total.max(1) as f64
    }
}

/// Run one scenario against a policy. Err = illegal action (engine
/// invariant violated). Deterministic: scenarios are fixed tables.
pub fn simulate<F: FnMut(&State) -> Action>(
    scn: &Scenario,
    policy: &mut F,
) -> Result<Stats, String> {
    let mut waiting: Vec<ReqSpec> = Vec::new();
    let mut running: Vec<Seq> = Vec::new();
    let mut ttfts: Vec<u32> = Vec::new();
    let mut stats = Stats {
        total: scn.reqs.len(),
        ..Default::default()
    };

    for t in 0..scn.iters {
        for r in scn.reqs.iter().filter(|r| r.arrival == t) {
            waiting.push(ReqSpec {
                id: r.id,
                arrival: r.arrival,
                prompt: r.prompt,
                output: r.output,
            });
        }

        let wviews: Vec<ReqView> = waiting
            .iter()
            .map(|r| ReqView {
                id: r.id,
                arrival: r.arrival,
                prompt_tokens: r.prompt,
            })
            .collect();
        let rviews: Vec<RunView> = running
            .iter()
            .map(|s| RunView {
                id: s.spec.id,
                arrival: s.spec.arrival,
                prompt_tokens: s.spec.prompt,
                decoded: s.decoded,
                prefill_left: s.prefill_left,
            })
            .collect();
        let action = policy(&State {
            iter: t,
            max_running: scn.max_running,
            mem_cap: scn.mem_cap,
            waiting: &wviews,
            running: &rviews,
        });

        // legality
        for id in &action.preempt {
            if !running.iter().any(|s| s.spec.id == *id) {
                return Err(format!("iter {t}: preempted id {id} is not running"));
            }
        }
        for id in &action.admit {
            if !waiting.iter().any(|r| r.id == *id) {
                return Err(format!("iter {t}: admitted id {id} is not waiting"));
            }
        }
        let post_running = running.len() - action.preempt.len() + action.admit.len();
        if post_running > scn.max_running {
            return Err(format!(
                "iter {t}: {post_running} running > max_running {}",
                scn.max_running
            ));
        }
        let preempted_mem: u32 = running
            .iter()
            .filter(|s| action.preempt.contains(&s.spec.id))
            .map(|s| s.spec.prompt + s.decoded)
            .sum();
        let admitted_mem: u32 = waiting
            .iter()
            .filter(|r| action.admit.contains(&r.id))
            .map(|r| r.prompt)
            .sum();
        let cur_mem: u32 = running.iter().map(|s| s.spec.prompt + s.decoded).sum();
        let post_mem = cur_mem - preempted_mem + admitted_mem;
        // Illegal only if THE ACTION pushes resident past the cap.
        // Passive growth (decode appending tokens) is handled below by
        // automatic preemption — vLLM's recompute-on-allocation-failure.
        if post_mem > scn.mem_cap && post_mem > cur_mem {
            return Err(format!(
                "iter {t}: action pushed resident to {post_mem} tokens > mem_cap {}",
                scn.mem_cap
            ));
        }

        // apply preempt (progress discarded — recompute mode)
        running.retain(|s| {
            if action.preempt.contains(&s.spec.id) {
                waiting.push(ReqSpec {
                    id: s.spec.id,
                    arrival: s.spec.arrival,
                    prompt: s.spec.prompt,
                    output: s.spec.output,
                });
                false
            } else {
                true
            }
        });
        // apply admit
        waiting.retain(|r| {
            if action.admit.contains(&r.id) {
                running.push(Seq {
                    prefill_left: r.prompt.div_ceil(CHUNK),
                    decoded: 0,
                    ttft: None,
                    spec: ReqSpec {
                        id: r.id,
                        arrival: r.arrival,
                        prompt: r.prompt,
                        output: r.output,
                    },
                });
                false
            } else {
                true
            }
        });

        // progress
        let mut finished: Vec<Seq> = Vec::new();
        for s in &mut running {
            if s.prefill_left > 0 {
                s.prefill_left -= 1;
                if s.prefill_left == 0 {
                    s.decoded = 1; // first token lands the iter prefill ends
                    s.ttft = Some(t - s.spec.arrival);
                }
            } else {
                s.decoded += 1;
            }
            if s.decoded >= s.spec.output {
                // mark; removal below (can't remove while iterating)
            }
        }
        let mut i = 0;
        while i < running.len() {
            if running[i].decoded >= running[i].spec.output {
                finished.push(running.remove(i));
            } else {
                i += 1;
            }
        }
        for f in finished {
            stats.completed += 1;
            stats.completed_ids.push(f.spec.id);
            stats.last_finish = stats.last_finish.max(t);
            let ttft = f.ttft.unwrap_or(u32::MAX);
            ttfts.push(ttft);
            if ttft <= scn.slo_ttft {
                stats.slo_met += 1;
            }
        }

        // Decode growth can push resident past the cap with no action at
        // all — the engine then force-preempts the NEWEST running seq
        // (recompute mode), exactly vLLM's allocation-failure path. A
        // policy that leaves no headroom pays for it in wasted work.
        loop {
            let resident: u32 = running.iter().map(|s| s.spec.prompt + s.decoded).sum();
            if resident <= scn.mem_cap || running.is_empty() {
                break;
            }
            let victim = running.pop().expect("non-empty");
            waiting.push(ReqSpec {
                id: victim.spec.id,
                arrival: victim.spec.arrival,
                prompt: victim.spec.prompt,
                output: victim.spec.output,
            });
        }
    }
    stats.ttft_p95 = percentile95(ttfts);
    Ok(stats)
}

/* ---------------------------- scenarios ----------------------------- */

struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: u32) -> u32 {
        (self.next() % n as u64) as u32
    }
}

/// A source of values below a bound: the fixed scenarios read the lab's old
/// xorshift stream, the seeded twins read `kslab::Rng::seeded(seed)`.
type Draw<'a> = &'a mut dyn FnMut(u32) -> u32;

fn fixed_draw(rng: &mut Rng) -> impl FnMut(u32) -> u32 + '_ {
    move |n| rng.below(n)
}

fn seeded_draw(rng: &mut SeedRng) -> impl FnMut(u32) -> u32 + '_ {
    move |n| rng.below(n as usize) as u32
}

fn light_from(below: Draw) -> Scenario {
    let mut reqs = Vec::new();
    for i in 0..20u32 {
        reqs.push(ReqSpec {
            id: i,
            arrival: below(200),
            prompt: 32 + below(224),
            output: 16 + below(48),
        });
    }
    Scenario {
        name: "light",
        reqs,
        max_running: 8,
        mem_cap: 8192,
        slo_ttft: 40,
        iters: 800,
    }
}

/// Light spread traffic — any sane policy passes.
pub fn scn_light() -> Scenario {
    light_from(&mut fixed_draw(&mut Rng(0x1164)))
}

/// Admit every waiting request that fits, in arrival order, as soon as it
/// can run. The harness's yardstick for "light": not a policy to copy.
fn eager(s: &State) -> Action {
    let mut used: u32 = s.running.iter().map(|r| r.prompt_tokens + r.decoded).sum();
    let mut slots = s.max_running.saturating_sub(s.running.len());
    let mut admit = Vec::new();
    for r in s.waiting {
        if slots == 0 {
            break;
        }
        if used + r.prompt_tokens > s.mem_cap {
            continue;
        }
        used += r.prompt_tokens;
        slots -= 1;
        admit.push(r.id);
    }
    Action { admit, preempt: Vec::new() }
}

/// Light means nobody has to wait: an admit-as-soon-as-possible run meets
/// every SLO and never has more than six of the eight slots busy.
fn is_light(scn: &Scenario) -> bool {
    let mut busiest = 0;
    let run = simulate(scn, &mut |s: &State| {
        let action = eager(s);
        busiest = busiest.max(s.running.len() + action.admit.len());
        action
    });
    matches!(run, Ok(s) if s.slo_met == s.total) && busiest <= 6
}

/// The same light traffic, drawn from a seed (the checks use this one).
///
/// A draw can pile nine requests into one stretch of iterations, and then
/// some request must wait, and which one depends on the policy. Such a draw is
/// not light: it is redrawn (deterministically, from the same stream) until
/// every policy that admits promptly can serve all of it, so a policy that
/// passes `slo_light` once passes it on every seed.
pub fn scn_light_seeded(seed: u32) -> Scenario {
    let mut rng = SeedRng::seeded(seed);
    let mut scn = light_from(&mut seeded_draw(&mut rng));
    for _ in 0..64 {
        if is_light(&scn) {
            break;
        }
        scn = light_from(&mut seeded_draw(&mut rng));
    }
    scn
}

/// A synchronized burst: 48 requests in the first 6 iterations, memory
/// sized so only ~28 prompts fit resident — admission control and
/// size-aware packing decide how many make the SLO.
///
/// Stays a fixed table on purpose: drawn from fresh seeds, the reference
/// itself misses 90 % on about one burst in twenty (measured on 1,000 draws),
/// and a check that cannot reach a reference pass rate of 1 is not seeded.
pub fn scn_burst() -> Scenario {
    let mut rng = Rng(0xB57);
    let mut reqs = Vec::new();
    for i in 0..48u32 {
        reqs.push(ReqSpec {
            id: i,
            arrival: rng.below(6),
            prompt: 64 + rng.below(448),
            output: 32 + rng.below(64),
        });
    }
    Scenario {
        name: "burst",
        reqs,
        max_running: 24,
        mem_cap: 8192,
        slo_ttft: 90,
        iters: 1200,
    }
}

/// The convoy: 88 short requests + one whale with an 8192-token prompt.
/// Memory fits EITHER the whale OR all the shorts, not both — and a full
/// prompt is reserved at admission. Who enters first decides everything.
pub fn scn_convoy() -> Scenario {
    let mut reqs = Vec::new();
    reqs.push(ReqSpec {
        id: 0,
        arrival: 0,
        prompt: 8192,
        output: 24,
    });
    for i in 1..=88u32 {
        reqs.push(ReqSpec {
            id: i,
            arrival: 0,
            prompt: 128,
            output: 24,
        });
    }
    Scenario {
        name: "convoy",
        reqs,
        max_running: 96,
        mem_cap: 12288,
        slo_ttft: 40,
        iters: 1200,
    }
}

fn starvation_from(below: Draw) -> Scenario {
    let mut reqs = Vec::new();
    for i in 0..3u32 {
        reqs.push(ReqSpec {
            id: i,
            arrival: 0,
            prompt: 1024,
            output: 32,
        });
    }
    for i in 3..403u32 {
        reqs.push(ReqSpec {
            id: i,
            // a dense leading pack so no policy gets a free early window,
            // then a stream that outlasts the horizon
            arrival: if i < 40 { i % 3 } else { below(2000) },
            prompt: 96 + below(160),
            output: 24 + below(32),
        });
    }
    Scenario {
        name: "starvation",
        reqs,
        max_running: 5,
        mem_cap: 12288,
        slo_ttft: 250,
        iters: 2500,
    }
}

/// Starvation watch: an effectively endless short stream (arrivals run
/// past the horizon), three longs at t=0. Pure shortest-first NEVER
/// admits the longs; only aging saves them.
pub fn scn_starvation() -> Scenario {
    starvation_from(&mut fixed_draw(&mut Rng(0x57A1)))
}

/// The same stream, drawn from a seed.
pub fn scn_starvation_seeded(seed: u32) -> Scenario {
    starvation_from(&mut seeded_draw(&mut SeedRng::seeded(seed)))
}

fn fleet_from(below: Draw) -> Scenario {
    let mut reqs = Vec::new();
    for i in 0..400u32 {
        let heavy = below(100) < 12;
        reqs.push(ReqSpec {
            id: i,
            arrival: below(1400),
            prompt: if heavy {
                1024 + below(2048)
            } else {
                64 + below(448)
            },
            output: 16 + below(80),
        });
    }
    Scenario {
        name: "fleet",
        reqs,
        max_running: 12,
        mem_cap: 16384,
        slo_ttft: 50,
        iters: 2500,
    }
}

/// The big one: 400 requests over 800 iterations at 2.4× offered load —
/// the SLO cannot be saved for everyone, so goodput IS the scheduling
/// quality metric.
pub fn scn_fleet() -> Scenario {
    fleet_from(&mut fixed_draw(&mut Rng(0xF1E7)))
}

/// The seeded twin of `scn_fleet`: the same 400 requests, the same 12 %
/// heavies, the same load and the same SLO, drawn from a seed. The fixed
/// `scn_fleet` stays in the replay score (and the leaderboard); this twin is
/// graded by `overload_seeded`, on a fresh seed at grade time.
pub fn scn_fleet_seeded(seed: u32) -> Scenario {
    fleet_from(&mut seeded_draw(&mut SeedRng::seeded(seed)))
}

fn scenario_from_trace(
    name: &'static str,
    rows: &[(u32, u32, u32)],
    max_running: usize,
    mem_cap: u32,
    slo_ttft: u32,
    iters: u32,
) -> Scenario {
    let reqs = rows
        .iter()
        .enumerate()
        .map(|(id, &(arrival, prompt, output))| ReqSpec {
            id: id as u32,
            arrival,
            prompt,
            output,
        })
        .collect();
    Scenario {
        name,
        reqs,
        max_running,
        mem_cap,
        slo_ttft,
        iters,
    }
}

/// BurstGPT v2.0, busiest aligned hour: 480 recorded requests, replayed
/// with the exact transformations documented in public/traces/README.md.
pub fn scn_burstgpt() -> Scenario {
    scenario_from_trace(
        "burstgpt",
        trace_scenarios::BURSTGPT_REQUESTS,
        8,
        4_096,
        40,
        2_200,
    )
}

/// Response-heavy LMSYS shape built only from the public 69.5/214.5-token
/// means. This is explicitly synthetic timing, not redistributed LMSYS data.
pub fn scn_lmsys_shape() -> Scenario {
    scenario_from_trace(
        "lmsys-shape",
        trace_scenarios::LMSYS_SHAPE_REQUESTS,
        64,
        32_768,
        120,
        5_000,
    )
}

/* ------------------------------ checks ------------------------------ */

/// Run one scenario against YOUR scheduler (a fresh one), as the checks do.
pub fn run(scn: &Scenario) -> Result<Stats, String> {
    let mut sch = Scheduler::new();
    simulate(scn, &mut |s| sch.schedule(s))
}

/// The checks, in grading order. Ids and labels match `src/data/labs.ts`;
/// stages are the F2 order of play (1 = the two-minute win). The replay
/// check stays unseeded: its floors are calibrated tables (labs/README,
/// "Lab 06 trace calibration").
pub static CHECKS: [CheckDef; 7] = [
    CheckDef { id: "runs_clean", label: RUNS_CLEAN, stage: 1, seeded: true, default_seed: 0x1164, run: check_runs_clean },
    CheckDef { id: "slo_light", label: SLO_LIGHT, stage: 2, seeded: true, default_seed: 0x1164, run: check_slo_light },
    CheckDef { id: "burst", label: BURST, stage: 2, seeded: false, default_seed: 0, run: check_burst },
    CheckDef { id: "convoy", label: CONVOY, stage: 3, seeded: false, default_seed: 0, run: check_convoy },
    CheckDef { id: "starvation", label: STARVATION, stage: 3, seeded: true, default_seed: 0x57A1, run: check_starvation },
    CheckDef { id: "goodput_score", label: GOODPUT_SCORE, stage: 4, seeded: false, default_seed: 0, run: check_goodput_score },
    CheckDef { id: "overload_seeded", label: OVERLOAD_SEEDED, stage: 4, seeded: true, default_seed: 0xF1E7, run: check_overload_seeded },
];

#[cfg(not(feature = "reference"))]
const LAB_ID: &str = "batching-scheduler";
/// A `--features reference` build names itself, and earns no credit anywhere.
#[cfg(feature = "reference")]
const LAB_ID: &str = "batching-scheduler@reference";

pub static LAB: Lab = Lab { id: LAB_ID, version: 3, checks: &CHECKS };

const RUNS_CLEAN: &str = "legal moves only; light load completes";
const SLO_LIGHT: &str = "goodput ≥ 95% on light load";
const BURST: &str = "burst absorption: goodput ≥ 90%";
const CONVOY: &str = "convoy: shorts survive the whale (≥ 85 of 89 SLO-met)";
const STARVATION: &str = "aging: 3 longs complete under an endless short stream";
const GOODPUT_SCORE: &str = "three replay traces clear calibrated goodput floors";
const OVERLOAD_SEEDED: &str = "seeded 2.4× overload: goodput clears the calibrated floor";

/// 1. runs_clean: invariants — never admit a non-waiting id, never blow
///    slots or memory — on the light scenario, everything completes.
pub fn check_runs_clean(ctx: &Ctx) -> Check {
    const ID: &str = "runs_clean";
    const LABEL: &str = RUNS_CLEAN;
    let scn = scn_light_seeded(ctx.seed);
    match run(&scn) {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(s) if s.completed < s.total => Check::fail(
            ID,
            LABEL,
            format!(
                "{} of {} requests completed on LIGHT load — is your admit list ever non-empty?",
                s.completed, s.total
            ),
        ),
        Ok(_) => Check::pass(ID, LABEL, "20/20 completed, zero illegal actions"),
    }
}

/// 2. slo_light: goodput ≥ 95% on light load. (Plain FCFS passes this —
///    the point is that the SLO bar exists at all.)
pub fn check_slo_light(ctx: &Ctx) -> Check {
    const ID: &str = "slo_light";
    const LABEL: &str = SLO_LIGHT;
    let scn = scn_light_seeded(ctx.seed);
    match run(&scn) {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(s) => {
            let g = s.goodput();
            if g < 0.95 {
                Check::fail(
                    ID,
                    LABEL,
                    format!("goodput {:.1}% < 95% on light load", g * 100.0),
                )
            } else {
                Check::pass(
                    ID,
                    LABEL,
                    format!("goodput {:.1}% (ttft p95 {} iters)", g * 100.0, s.ttft_p95),
                )
            }
        }
    }
}

/// 3. burst: 48 requests in 6 iterations. Admission control or collapse.
pub fn check_burst(_: &Ctx) -> Check {
    const ID: &str = "burst";
    const LABEL: &str = BURST;
    let scn = scn_burst();
    match run(&scn) {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(s) => {
            let g = s.goodput();
            if g < 0.90 {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "goodput {:.1}% < 90% under burst — admit-what-fits beats admit-all",
                        g * 100.0
                    ),
                )
            } else {
                Check::pass(
                    ID,
                    LABEL,
                    format!("goodput {:.1}% under a 48-request burst", g * 100.0),
                )
            }
        }
    }
}

/// 4. convoy: the whale must not go first, and decode growth must not
///    thrash the pool. Size-aware admission WITH headroom. (Calibrated:
///    plain FCFS meets 54 of 89.)
pub fn check_convoy(_: &Ctx) -> Check {
    const ID: &str = "convoy";
    const LABEL: &str = CONVOY;
    let scn = scn_convoy();
    match run(&scn) {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(s) => {
            if s.slo_met < 85 {
                Check::fail(
                    ID,
                    LABEL,
                    format!("{} of {} met SLO — either the whale went first, or decode growth thrashed the pool (leave headroom!)", s.slo_met, s.total),
                )
            } else if s.completed < s.total {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "{} of {} completed — starving the whale is also wrong",
                        s.completed, s.total
                    ),
                )
            } else {
                Check::pass(
                    ID,
                    LABEL,
                    format!(
                        "{} of {} met SLO, whale completed, no thrash",
                        s.slo_met, s.total
                    ),
                )
            }
        }
    }
}

/// 5. starvation: the stream never stops; the three longs must still
///    finish inside the horizon. Pure shortest-first fails this.
pub fn check_starvation(ctx: &Ctx) -> Check {
    const ID: &str = "starvation";
    const LABEL: &str = STARVATION;
    let scn = scn_starvation_seeded(ctx.seed);
    match run(&scn) {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(s) => {
            let longs_done = [0u32, 1, 2]
                .iter()
                .filter(|id| s.completed_ids.contains(id))
                .count();
            if longs_done < 3 {
                Check::fail(
                    ID,
                    LABEL,
                    format!("{longs_done} of 3 longs completed — your size bias starves them. Add aging: priority must grow with wait time"),
                )
            } else if s.completed < 100 {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "only {} requests completed — the engine is gridlocked",
                        s.completed
                    ),
                )
            } else {
                Check::pass(
                    ID,
                    LABEL,
                    format!(
                        "all 3 longs completed; {} total finished in the window",
                        s.completed
                    ),
                )
            }
        }
    }
}

pub const SYNTHETIC_GOODPUT_FLOOR: f64 = 0.55;
pub const BURSTGPT_GOODPUT_FLOOR: f64 = 0.85;
pub const LMSYS_SHAPE_GOODPUT_FLOOR: f64 = 0.70;

pub struct GoodputScores {
    pub synthetic: Stats,
    pub burstgpt: Stats,
    pub lmsys_shape: Stats,
}

impl GoodputScores {
    pub fn mean(&self) -> f64 {
        (self.synthetic.goodput() + self.burstgpt.goodput() + self.lmsys_shape.goodput()) / 3.0
    }
}

pub fn score_goodput_traces() -> Result<GoodputScores, String> {
    Ok(GoodputScores {
        synthetic: run(&scn_fleet())?,
        burstgpt: run(&scn_burstgpt())?,
        lmsys_shape: run(&scn_lmsys_shape())?,
    })
}

/// 6. goodput_score: one synthetic overload plus the recorded BurstGPT
///    slice and the licensed-safe LMSYS aggregate shape. Each distribution
///    has its own calibrated floor; the numeric mean is the leaderboard score.
pub fn check_goodput_score(_: &Ctx) -> Check {
    const ID: &str = "goodput_score";
    const LABEL: &str = GOODPUT_SCORE;
    match score_goodput_traces() {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(scores) => {
            let synthetic = scores.synthetic.goodput();
            let burstgpt = scores.burstgpt.goodput();
            let lmsys = scores.lmsys_shape.goodput();
            if synthetic < SYNTHETIC_GOODPUT_FLOOR {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "synthetic goodput {:.1}% < {:.1}% floor",
                        synthetic * 100.0,
                        SYNTHETIC_GOODPUT_FLOOR * 100.0,
                    ),
                )
            } else if burstgpt < BURSTGPT_GOODPUT_FLOOR {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "BurstGPT goodput {:.1}% < {:.1}% floor",
                        burstgpt * 100.0,
                        BURSTGPT_GOODPUT_FLOOR * 100.0,
                    ),
                )
            } else if lmsys < LMSYS_SHAPE_GOODPUT_FLOOR {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "LMSYS-shape goodput {:.1}% < {:.1}% floor",
                        lmsys * 100.0,
                        LMSYS_SHAPE_GOODPUT_FLOOR * 100.0,
                    ),
                )
            } else {
                Check::pass(
                    ID,
                    LABEL,
                    format!(
                        "mean {:.1}% · synthetic {:.1}% · BurstGPT {:.1}% · LMSYS-shape {:.1}%",
                        scores.mean() * 100.0,
                        synthetic * 100.0,
                        burstgpt * 100.0,
                        lmsys * 100.0,
                    ),
                )
            }
        }
    }
}

/// Goodput the seeded overload must clear. Calibrated offline on 10,000 fresh
/// seeds (calibration.json): well under every reference-shaped policy's worst
/// draw, well over first-come-first-served.
pub const OVERLOAD_GOODPUT_FLOOR: f64 = 0.40;

/// 7. overload_seeded: the synthetic fleet overload's seeded twin. The same
///    400 requests at 2.4× load, drawn from the seed at grade time, so a
///    policy tuned to the one fixed trace in `goodput_score` has to hold up
///    on traffic it has not seen. The replay traces stay fixed tables.
pub fn check_overload_seeded(ctx: &Ctx) -> Check {
    const ID: &str = "overload_seeded";
    const LABEL: &str = OVERLOAD_SEEDED;
    let scn = scn_fleet_seeded(ctx.seed);
    match run(&scn) {
        Err(e) => Check::fail(ID, LABEL, format!("illegal action: {e}")),
        Ok(s) => {
            let g = s.goodput();
            if g < OVERLOAD_GOODPUT_FLOOR {
                Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "goodput {:.1}% < {:.1}% floor on a freshly drawn 400-request overload — size-aware admission beats first-come-first-served here, and it has to hold on every draw",
                        g * 100.0,
                        OVERLOAD_GOODPUT_FLOOR * 100.0
                    ),
                )
            } else {
                Check::pass(
                    ID,
                    LABEL,
                    format!("goodput {:.1}% on a seeded 400-request overload (ttft p95 {} iters)", g * 100.0, s.ttft_p95),
                )
            }
        }
    }
}

/// The full suite on default seeds, in grading order (v1 report order).
pub fn self_checks() -> Vec<Check> {
    CHECKS.iter().map(|c| (c.run)(&Ctx { seed: c.default_seed, fresh: false })).collect()
}

/* ------------------------------ probe ------------------------------- */

/// `probe <seed>`: a seeded mini-overload (60 requests in 300 iterations,
/// 6 slots, 6,144 tokens of memory) on YOUR scheduler, summarised in one
/// line. Deterministic for a given seed and scheduler.
pub fn probe(seed: u32) -> String {
    let mut rng = SeedRng::seeded(seed);
    let mut reqs = Vec::new();
    for i in 0..60u32 {
        let heavy = rng.below(100) < 15;
        reqs.push(ReqSpec {
            id: i,
            arrival: rng.below(300) as u32,
            prompt: if heavy { 768 + rng.below(1024) as u32 } else { 64 + rng.below(320) as u32 },
            output: 16 + rng.below(48) as u32,
        });
    }
    let scn = Scenario { name: "probe", reqs, max_running: 6, mem_cap: 6144, slo_ttft: 40, iters: 700 };
    match run(&scn) {
        Ok(s) => format!(
            "reqs={} completed={} slo_met={} goodput={:.3} ttft_p95={} last_finish={}",
            s.total,
            s.completed,
            s.slo_met,
            s.goodput(),
            s.ttft_p95,
            s.last_finish
        ),
        Err(e) => format!("err illegal action: {e}"),
    }
}

/* ------------------------------ wasm ABI ---------------------------- */

kslab::export_abi_v2!();

#[no_mangle]
pub extern "C" fn ks_run(in_ptr: u32, in_len: u32) -> u64 {
    kslab::run(unsafe { kslab::input(in_ptr, in_len) }, &LAB)
}

/* --------------------------- fleet bridge --------------------------- */
/* The Fleet page (/fleet, engine mode) drives YOUR scheduler live:

     init                                   → ok   (fresh Scheduler)
     probe <seed>                           → one summary line of a seeded mini-overload
     score                                  → four numeric score lines
     schedule <iter> <max_running> <mem_cap> <mem_used>
       W <id> <arrival> <prompt> ; …        waiting view (id arrival prompt)
       R <id> <arrival> <prompt> <decoded> <prefill_left> ; …
     → "admit <id,id,…>\npreempt <id,id,…>" (empty lists allowed)
*/

use std::cell::RefCell;

thread_local! {
    static FLEET_SCHED: RefCell<Option<Scheduler>> = const { RefCell::new(None) };
}

#[no_mangle]
pub extern "C" fn ks_invoke(in_ptr: u32, in_len: u32) -> u64 {
    kslab::install_panic_hook();
    let bytes = unsafe { std::slice::from_raw_parts(in_ptr as *const u8, in_len as usize) };
    let input = String::from_utf8_lossy(bytes).into_owned();
    let reply = FLEET_SCHED.with(|s| bridge(&mut s.borrow_mut(), &input));
    kslab::emit_str(&reply)
}

fn bridge(slot: &mut Option<Scheduler>, input: &str) -> String {
    let mut lines = input.lines();
    let Some(head) = lines.next() else {
        return "err empty".into();
    };
    let parts: Vec<&str> = head.split_whitespace().collect();
    match parts.first().copied() {
        Some("init") => {
            *slot = Some(Scheduler::new());
            "ok".into()
        }
        Some("probe") if parts.len() == 2 => match parts[1].parse::<u32>() {
            Ok(seed) => probe(seed),
            Err(_) => format!("err bad seed '{}'", parts[1]),
        },
        Some("score") if parts.len() == 1 => match score_goodput_traces() {
            Ok(scores) => format!(
                "synthetic {:.6}\nburstgpt {:.6}\nlmsys-shape {:.6}\nmean {:.6}",
                scores.synthetic.goodput() * 100.0,
                scores.burstgpt.goodput() * 100.0,
                scores.lmsys_shape.goodput() * 100.0,
                scores.mean() * 100.0,
            ),
            Err(error) => format!("err {error}"),
        },
        Some("schedule") if parts.len() == 5 => {
            let Some(sch) = slot.as_mut() else {
                return "err not initialized".into();
            };
            let (Ok(iter), Ok(max_running), Ok(mem_cap), Ok(mem_used)) = (
                parts[1].parse::<u32>(),
                parts[2].parse::<usize>(),
                parts[3].parse::<u32>(),
                parts[4].parse::<u32>(),
            ) else {
                return format!("err bad header '{head}'");
            };
            let _ = mem_used; // visible in state via running sum; reserved
            let mut waiting: Vec<ReqView> = Vec::new();
            let mut running: Vec<RunView> = Vec::new();
            for line in lines {
                for entry in line.split(';') {
                    let f: Vec<&str> = entry.split_whitespace().collect();
                    match f.first().copied() {
                        Some("W") if f.len() == 4 => {
                            if let (Ok(id), Ok(arrival), Ok(prompt_tokens)) =
                                (f[1].parse(), f[2].parse(), f[3].parse())
                            {
                                waiting.push(ReqView {
                                    id,
                                    arrival,
                                    prompt_tokens,
                                });
                            }
                        }
                        Some("R") if f.len() == 6 => {
                            if let (
                                Ok(id),
                                Ok(arrival),
                                Ok(prompt_tokens),
                                Ok(decoded),
                                Ok(prefill_left),
                            ) = (
                                f[1].parse(),
                                f[2].parse(),
                                f[3].parse(),
                                f[4].parse(),
                                f[5].parse(),
                            ) {
                                running.push(RunView {
                                    id,
                                    arrival,
                                    prompt_tokens,
                                    decoded,
                                    prefill_left,
                                });
                            }
                        }
                        _ => {}
                    }
                }
            }
            let action = sch.schedule(&State {
                iter,
                max_running,
                mem_cap,
                waiting: &waiting,
                running: &running,
            });
            let csv = |v: Vec<u32>| v.iter().map(u32::to_string).collect::<Vec<_>>().join(",");
            format!(
                "admit {}\npreempt {}",
                csv(action.admit),
                csv(action.preempt)
            )
        }
        _ => "err unknown command".into(),
    }
}
