//! kv-block-manager — forge lab 02.
//!
//! PagedAttention, from the inside. You get a fixed pool of physical KV
//! blocks and must implement vLLM's block manager: per-sequence block
//! tables, `fork` with reference counting, and copy-on-write when a shared
//! tail block is appended to. This is T2 virtual memory (page tables,
//! fork(2), CoW) wearing a GPU — and the direct descendant of your lab 01
//! free-list allocator.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/manager.rs     (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The model (same simplifications the vLLM paper makes):
//!   * A sequence is `len` tokens; it needs ceil(len / block_size) blocks.
//!   * `fork` shares ALL of the parent's blocks (refcount++) — beam search
//!     and parallel sampling do exactly this.
//!   * A shared block is read-only. Appending into a shared (partial) tail
//!     block triggers copy-on-write: new private block, refcount-- on the
//!     shared one.
//!   * All-or-nothing: if the pool can't satisfy an operation, return
//!     false and leave ALL state untouched. Half-applied allocations are
//!     how production engines corrupt themselves.
//!   * `free` decrements refcounts; a block returns to the pool only at 0.
//!     Leak one and check 6 (the churn gauntlet) will starve you.
//!
//! The checks below are the single source of truth:
//!   * `cargo test` runs them on your machine, on their default seeds and on
//!     32 extra seeds.
//!   * `cargo build --release --target wasm32-unknown-unknown` bakes them
//!     into the .wasm you drop into kernelspace → the site runs each check on
//!     its own (template v2), with a fresh seed for the churn gauntlet, and
//!     renders exactly these results.
//!
//! A `todo!()` in your code traps that check; the site shows it as "not
//! implemented yet" with the panic text, and the other checks still run.
//!
//! Which check catches which mistake:
//!
//! ```text
//!   paging          a wrong ceil in the block count, a translate that
//!                   indexes the wrong block, or two sequences aliasing
//!   capacity        an allocate that succeeds on a full pool, a failed
//!                   allocate that still changes state, or a free that
//!                   never recycles
//!   fork_shares     a fork that copies blocks instead of the table
//!   free_refcount   a free that returns blocks another sequence still uses
//!   cow             an append into a shared tail that writes through it
//!                   (or a copy that touches the parent)
//!   gauntlet        every leak, double free or stale refcount the five
//!                   above miss, such as an allocate or append that takes
//!                   blocks before it fails: seeded churn, conservation
//!                   after each op
//!   adapter_...     optional: adapter pages from the same pool (T6.L9)
//! ```

mod manager;

use kslab::{Check, CheckDef, Ctx, Lab, Rng};
use manager::BlockManager;

const POOL: usize = 8; // physical blocks in the small scenarios
const BS: usize = 16; // tokens per block

#[cfg(not(feature = "reference"))]
const LAB_ID: &str = "kv-block-manager";
/// A `--features reference` build names itself, and earns no credit anywhere.
#[cfg(feature = "reference")]
const LAB_ID: &str = "kv-block-manager@reference";

/// The checks, in grading order. Ids and labels match `src/data/labs.ts`;
/// stage 5 is the optional advanced extension, so finishing the six required
/// checks reaches stage 4.
pub static CHECKS: [CheckDef; 7] = [
    CheckDef { id: "paging", label: PAGING, stage: 1, seeded: false, default_seed: 0, run: check_paging },
    CheckDef { id: "capacity", label: CAPACITY, stage: 2, seeded: false, default_seed: 0, run: check_capacity },
    CheckDef { id: "fork_shares", label: FORK_SHARES, stage: 3, seeded: false, default_seed: 0, run: check_fork_shares },
    CheckDef { id: "cow", label: COW, stage: 4, seeded: false, default_seed: 0, run: check_cow },
    CheckDef { id: "free_refcount", label: FREE_REFCOUNT, stage: 3, seeded: false, default_seed: 0, run: check_free_refcount },
    CheckDef { id: "gauntlet", label: GAUNTLET, stage: 4, seeded: true, default_seed: 0x6A17, run: check_gauntlet },
    CheckDef {
        id: "adapter_unified_paging",
        label: ADAPTER_UNIFIED_PAGING,
        stage: 5,
        seeded: false,
        default_seed: 0,
        run: check_adapter_unified_paging,
    },
];

pub static LAB: Lab = Lab { id: LAB_ID, version: 3, checks: &CHECKS };

const PAGING: &str = "block-table math and translation";
const CAPACITY: &str = "pool exhaustion is atomic; freed blocks return";
const FORK_SHARES: &str = "fork shares blocks via refcounts (zero-copy)";
const COW: &str = "copy-on-write on append to shared tail";
const FREE_REFCOUNT: &str = "refcounted free — shared blocks survive until the last owner";
const GAUNTLET: &str = "2000-op churn: block conservation after every op";
const ADAPTER_UNIFIED_PAGING: &str = "advanced: adapter weights share the paged KV pool";

/* ------------------------------ checks ------------------------------ */

/// 1. paging: block-table math — ceil(tokens/BS) blocks, correct
///    translation, isolation between sequences.
pub fn check_paging(_: &Ctx) -> Check {
    const ID: &str = "paging";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 20) || !m.allocate(2, 16) || !m.allocate(3, 17) {
        return Check::fail(ID, PAGING, "allocate failed on an empty 8-block pool");
    }
    // 20→2 blocks, 16→1, 17→2 ⇒ 5 used, 3 free
    if m.free_blocks() != 3 {
        return Check::fail(
            ID,
            PAGING,
            format!(
                "expected 3 free blocks after 20+16+17 tokens, got {}",
                m.free_blocks()
            ),
        );
    }
    let a = m.translate(1, 0);
    let b = m.translate(1, 15);
    let c = m.translate(1, 16);
    if a.is_none() || a != b {
        return Check::fail(
            ID,
            PAGING,
            format!("tokens 0 and 15 must share a block, got {a:?} vs {b:?}"),
        );
    }
    if c.is_none() || c == a {
        return Check::fail(
            ID,
            PAGING,
            format!("token 16 must be in the next block, got {c:?}"),
        );
    }
    if m.translate(1, 20).is_some() {
        return Check::fail(ID, PAGING, "translate past the sequence end must be None");
    }
    // isolation: no physical block shared between seqs without fork
    for s in 1..=3u32 {
        for t in (s + 1)..=3u32 {
            for tok in 0..17usize {
                let (x, y) = (m.translate(s, tok), m.translate(t, tok));
                if x.is_some() && x == y {
                    return Check::fail(
                        ID,
                        PAGING,
                        format!("seqs {s} and {t} alias a block at token {tok} without fork"),
                    );
                }
            }
        }
    }
    Check::pass(
        ID,
        PAGING,
        "ceil math, translation, and isolation all correct",
    )
}

/// 2. capacity: the pool is finite — failed allocations are clean no-ops,
///    freed blocks come back.
pub fn check_capacity(_: &Ctx) -> Check {
    const ID: &str = "capacity";
    let mut m = BlockManager::new(4, BS);
    if !m.allocate(1, 4 * BS) {
        return Check::fail(ID, CAPACITY, "could not fill an empty pool");
    }
    if m.free_blocks() != 0 {
        return Check::fail(
            ID,
            CAPACITY,
            format!("pool should be full, {} blocks free", m.free_blocks()),
        );
    }
    if m.allocate(2, 1) {
        return Check::fail(
            ID,
            CAPACITY,
            "allocate succeeded on a full pool — blocks from nowhere",
        );
    }
    if m.free_blocks() != 0 {
        return Check::fail(
            ID,
            CAPACITY,
            "failed allocate mutated state — must be all-or-nothing",
        );
    }
    m.free(1);
    if m.free_blocks() != 4 {
        return Check::fail(
            ID,
            CAPACITY,
            format!("free(1) should return 4 blocks, got {}", m.free_blocks()),
        );
    }
    if !m.allocate(2, BS) {
        return Check::fail(
            ID,
            CAPACITY,
            "allocate failed right after free — blocks were not recycled",
        );
    }
    Check::pass(ID, CAPACITY, "exhaustion is clean, recycling works")
}

/// 3. fork_shares: fork copies the block TABLE, not the blocks — zero
///    allocation, identical translation.
pub fn check_fork_shares(_: &Ctx) -> Check {
    const ID: &str = "fork_shares";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 40) {
        return Check::fail(ID, FORK_SHARES, "allocate failed");
    }
    let before = m.free_blocks();
    if !m.fork(1, 2) {
        return Check::fail(ID, FORK_SHARES, "fork(1, 2) failed with free blocks available");
    }
    if m.free_blocks() != before {
        return Check::fail(
            ID,
            FORK_SHARES,
            format!("fork allocated blocks ({before} → {} free) — fork is table copy + refcount, not memcpy", m.free_blocks()),
        );
    }
    for t in 0..40usize {
        if m.translate(1, t) != m.translate(2, t) {
            return Check::fail(
                ID,
                FORK_SHARES,
                format!("token {t} diverged right after fork — nothing was written yet"),
            );
        }
    }
    Check::pass(ID, FORK_SHARES, "40 tokens shared, zero blocks allocated")
}

/// 4. cow: appending to a shared partial tail copies exactly one block;
///    the parent is untouched; the shared prefix stays shared.
pub fn check_cow(_: &Ctx) -> Check {
    const ID: &str = "cow";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 40) || !m.fork(1, 2) {
        return Check::fail(ID, COW, "setup failed");
    }
    let parent_tail = m.translate(1, 39);
    let before = m.free_blocks();
    if !m.append(2, 1) {
        return Check::fail(ID, COW, "append(2, 1) failed with free blocks available");
    }
    if m.free_blocks() != before - 1 {
        return Check::fail(
            ID,
            COW,
            format!(
                "CoW should consume exactly 1 block ({before} → {} free)",
                m.free_blocks()
            ),
        );
    }
    if m.translate(1, 39) != parent_tail {
        return Check::fail(
            ID,
            COW,
            "the PARENT's tail moved during the child's append — CoW must not touch the parent",
        );
    }
    if m.translate(2, 39) == m.translate(1, 39) {
        return Check::fail(
            ID,
            COW,
            "child still aliases the shared tail after append — no copy happened",
        );
    }
    for t in 0..32usize {
        if m.translate(1, t) != m.translate(2, t) {
            return Check::fail(
                ID,
                COW,
                format!("prefix token {t} diverged — CoW must copy only the tail block"),
            );
        }
    }
    Check::pass(
        ID,
        COW,
        "one block copied, prefix still shared, parent untouched",
    )
}

/// 5. free_refcount: freeing one sharer frees nothing; freeing the last
///    sharer frees everything.
pub fn check_free_refcount(_: &Ctx) -> Check {
    const ID: &str = "free_refcount";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 40) || !m.fork(1, 2) {
        return Check::fail(ID, FREE_REFCOUNT, "setup failed");
    }
    let before = m.free_blocks(); // 5
    m.free(1);
    if m.free_blocks() != before {
        return Check::fail(
            ID,
            FREE_REFCOUNT,
            format!(
                "free(1) returned blocks still shared by seq 2 ({before} → {} free)",
                m.free_blocks()
            ),
        );
    }
    for t in 0..40usize {
        if m.translate(2, t).is_none() {
            return Check::fail(
                ID,
                FREE_REFCOUNT,
                format!("seq 2 lost token {t} when seq 1 was freed — refcount underflow"),
            );
        }
    }
    m.free(2);
    if m.free_blocks() != POOL {
        return Check::fail(
            ID,
            FREE_REFCOUNT,
            format!("pool should be whole again ({}/{})", m.free_blocks(), POOL),
        );
    }
    Check::pass(ID, FREE_REFCOUNT, "blocks outlive every owner but the last")
}

/// 6. gauntlet: 2000 mixed ops at churn, drawn from the seed. The invariant that
///    must hold after EVERY op:
///      free_blocks + |distinct blocks referenced by live seqs| == POOL
///    Break refcounting anywhere (leak, double-free, aliasing) and this
///    equation breaks — a leaking manager eventually can't allocate at all.
pub fn check_gauntlet(ctx: &Ctx) -> Check {
    const ID: &str = "gauntlet";
    const N: usize = 64;
    let mut m = BlockManager::new(N, BS);
    let mut rng = Rng::seeded(ctx.seed);
    // seq slots 0..16; live[i] = Some(token_len) when alive
    let mut live: [Option<usize>; 16] = [None; 16];
    let live_ids = |live: &[Option<usize>; 16]| -> Vec<u32> {
        live.iter()
            .enumerate()
            .filter(|(_, l)| l.is_some())
            .map(|(i, _)| i as u32)
            .collect()
    };
    let conservation = |m: &BlockManager, live: &[Option<usize>; 16]| -> Result<usize, String> {
        let mut used = [false; N];
        let mut used_n = 0usize;
        for (id, len) in live.iter().enumerate() {
            if let Some(len) = len {
                for t in 0..*len {
                    match m.translate(id as u32, t) {
                        Some(b) if b < N => {
                            if !used[b] {
                                used[b] = true;
                                used_n += 1;
                            }
                        }
                        Some(b) => {
                            return Err(format!("seq {id} token {t} → block {b} ≥ pool size {N}"))
                        }
                        None => return Err(format!("seq {id} lost token {t}")),
                    }
                }
            }
        }
        Ok(used_n)
    };

    for op in 0..2000usize {
        let action = rng.below(100);
        let ids = live_ids(&live);
        if action < 25 || ids.is_empty() {
            // allocate a fresh seq
            let Some(slot) = live.iter().position(|l| l.is_none()) else {
                continue;
            };
            let tokens = 1 + rng.below(144);
            if m.allocate(slot as u32, tokens) {
                live[slot] = Some(tokens);
            }
        } else if action < 55 {
            // append
            let id = ids[rng.below(ids.len())];
            let n = 1 + rng.below(40);
            if m.append(id, n) {
                live[id as usize] = live[id as usize].map(|l| l + n);
            }
        } else if action < 70 {
            // fork into a free slot
            let id = ids[rng.below(ids.len())];
            let Some(slot) = live.iter().position(|l| l.is_none()) else {
                continue;
            };
            if m.fork(id, slot as u32) {
                live[slot] = live[id as usize];
            }
        } else {
            // free
            let id = ids[rng.below(ids.len())];
            m.free(id);
            live[id as usize] = None;
        }
        match conservation(&m, &live) {
            Ok(used) => {
                if m.free_blocks() + used != N {
                    return Check::fail(
                        ID,
                        GAUNTLET,
                        format!(
                            "op {op}: conservation broken — {} free + {used} referenced ≠ {N} total. A block leaked or was double-freed.",
                            m.free_blocks()
                        ),
                    );
                }
            }
            Err(e) => return Check::fail(ID, GAUNTLET, format!("op {op}: {e}")),
        }
    }
    Check::pass(
        ID,
        GAUNTLET,
        "2000 ops, conservation held after every single one",
    )
}

/// Optional advanced extension — S-LoRA-style unified paging. Adapter
/// weights and sequence KV draw from one physical block pool, remain
/// isolated, and return capacity independently.
pub fn check_adapter_unified_paging(_: &Ctx) -> Check {
    const ID: &str = "adapter_unified_paging";
    let mut m = BlockManager::new(12, BS);
    if !m.allocate(1, 3 * BS) {
        return Check::fail(ID, ADAPTER_UNIFIED_PAGING, "could not allocate the three-page KV sequence");
    }
    if !m.load_adapter(7, 5) {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            "load_adapter is still the optional fail-closed stub",
        );
    }
    if m.free_blocks() != 4 {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            format!(
                "3 KV + 5 adapter pages should leave 4 free, got {}",
                m.free_blocks()
            ),
        );
    }
    let adapter_pages: Vec<_> = (0..5).map(|page| m.adapter_page(7, page)).collect();
    if adapter_pages.iter().any(Option::is_none)
        || m.adapter_page(7, 5).is_some()
        || (0..3).any(|token_block| {
            let kv = m.translate(1, token_block * BS);
            adapter_pages.contains(&kv)
        })
    {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            "adapter table is incomplete, unbounded, or aliases live KV",
        );
    }
    let before = m.free_blocks();
    if m.load_adapter(7, 1) || m.allocate(2, 5 * BS) || m.free_blocks() != before {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            "duplicate/exhausted allocation was not an atomic no-op",
        );
    }
    m.unload_adapter(7);
    if m.free_blocks() != 9 || m.translate(1, 2 * BS).is_none() {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            "unloading adapter pages damaged KV or leaked capacity",
        );
    }
    if !m.load_adapter(8, 9) || m.free_blocks() != 0 {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            "recycled adapter pages could not refill the unified pool",
        );
    }
    m.free(1);
    m.unload_adapter(8);
    if m.free_blocks() != 12 {
        return Check::fail(
            ID,
            ADAPTER_UNIFIED_PAGING,
            "final KV + adapter drain did not conserve all 12 pages",
        );
    }
    Check::pass(
        ID,
        ADAPTER_UNIFIED_PAGING,
        "KV and two adapter lifecycles conserved one 12-page pool",
    )
}

/// The full suite on default seeds, in grading order (v1 report order).
pub fn self_checks() -> Vec<Check> {
    CHECKS.iter().map(|c| (c.run)(&Ctx { seed: c.default_seed, fresh: false })).collect()
}

/* ------------------------------ probe ------------------------------- */

/// `probe <seed>`: 200 seeded ops on your manager (32 blocks of 16 tokens),
/// summarised in one line: live sequences, free blocks, blocks referenced and
/// how many of those are shared through fork, and refused operations. The
/// harness tracks each sequence's length itself and reads blocks only through
/// `translate`, so the line is deterministic for a given seed and manager.
pub fn probe(seed: u32) -> String {
    const N: usize = 32;
    const SLOTS: usize = 12;
    let mut m = BlockManager::new(N, BS);
    let mut rng = Rng::seeded(seed);
    let mut live: [Option<usize>; SLOTS] = [None; SLOTS];
    let mut refused = 0;
    for _ in 0..200 {
        let ids: Vec<usize> = (0..SLOTS).filter(|&i| live[i].is_some()).collect();
        let free_slot = live.iter().position(|l| l.is_none());
        let action = rng.below(100);
        if action < 30 || ids.is_empty() {
            let Some(slot) = free_slot else { continue };
            let tokens = 1 + rng.below(64);
            if m.allocate(slot as u32, tokens) {
                live[slot] = Some(tokens);
            } else {
                refused += 1;
            }
        } else if action < 60 {
            let id = ids[rng.below(ids.len())];
            let n = 1 + rng.below(16);
            if m.append(id as u32, n) {
                live[id] = live[id].map(|l| l + n);
            } else {
                refused += 1;
            }
        } else if action < 75 {
            let id = ids[rng.below(ids.len())];
            let Some(slot) = free_slot else { continue };
            if m.fork(id as u32, slot as u32) {
                live[slot] = live[id];
            } else {
                refused += 1;
            }
        } else {
            let id = ids[rng.below(ids.len())];
            m.free(id as u32);
            live[id] = None;
        }
    }
    let mut table_entries = 0;
    let mut seen = [false; N];
    for (id, len) in live.iter().enumerate() {
        if let Some(len) = len {
            for b in 0..len.div_ceil(BS) {
                table_entries += 1;
                if let Some(p) = m.translate(id as u32, b * BS) {
                    if p < N {
                        seen[p] = true;
                    }
                }
            }
        }
    }
    let used = seen.iter().filter(|&&u| u).count();
    let seqs = live.iter().filter(|l| l.is_some()).count();
    format!(
        "ops=200 seqs={seqs} free={} used={used} shared={} refused={refused}",
        m.free_blocks(),
        table_entries - used
    )
}

/* ------------------------------ wasm ABI ---------------------------- */

kslab::export_abi_v2!();

#[no_mangle]
pub extern "C" fn ks_run(in_ptr: u32, in_len: u32) -> u64 {
    kslab::run(unsafe { kslab::input(in_ptr, in_len) }, &LAB)
}

/* --------------------------- fleet bridge --------------------------- */
/* The Fleet page (/fleet) drives YOUR manager live through this bridge:
   a line protocol over the same memory ABI. The host writes a command
   into module memory with ks_alloc, calls ks_invoke, reads the reply.

     init <num_blocks> <block_size>        → ok
     allocate <seq> <tokens>               → true | false
     append <seq> <n>                      → true | false
     fork <src> <dst>                      → true | false
     free <seq>                            → ok
     translate <seq> <token>               → <block id> | none
     free_blocks                           → <n>
     dump                                  → your dump() output, verbatim
     probe <seed>                          → one summary line of a seeded
                                             200-op scenario (see `probe`)
*/

use std::cell::RefCell;

thread_local! {
    static FLEET_MANAGER: RefCell<Option<BlockManager>> = const { RefCell::new(None) };
}

#[no_mangle]
pub extern "C" fn ks_invoke(in_ptr: u32, in_len: u32) -> u64 {
    kslab::install_panic_hook();
    let bytes = unsafe { kslab::input(in_ptr, in_len) };
    let cmd = String::from_utf8_lossy(bytes).into_owned();
    let reply = match cmd.split_whitespace().collect::<Vec<_>>()[..] {
        // its own manager: a probe never disturbs the Fleet's
        ["probe", seed] => match seed.parse::<u32>() {
            Ok(seed) => probe(seed),
            Err(_) => format!("err bad seed '{}'", kslab::clip(seed, 20)),
        },
        _ => FLEET_MANAGER.with(|m| dispatch(&mut m.borrow_mut(), cmd.trim())),
    };
    kslab::emit_str(&reply)
}

fn dispatch(m: &mut Option<BlockManager>, cmd: &str) -> String {
    let parts: Vec<&str> = cmd.split_whitespace().collect();
    let num = |i: usize| -> Result<usize, String> {
        parts
            .get(i)
            .and_then(|s| s.parse::<usize>().ok())
            .ok_or_else(|| format!("err bad number in '{cmd}'"))
    };
    match parts.first().copied() {
        Some("init") if parts.len() == 3 => match (num(1), num(2)) {
            (Ok(blocks), Ok(bs)) if blocks > 0 && bs > 0 => {
                *m = Some(BlockManager::new(blocks, bs));
                "ok".into()
            }
            _ => format!("err bad init '{cmd}'"),
        },
        Some("dump") if parts.len() == 1 => match m.as_ref() {
            Some(bm) => bm.dump(),
            None => "err not initialized".into(),
        },
        Some(op) => {
            let Some(bm) = m.as_mut() else {
                return "err not initialized".into();
            };
            match (op, parts.len()) {
                ("allocate", 3) | ("append", 3) => match (num(1), num(2)) {
                    (Ok(a), Ok(b)) if a <= u32::MAX as usize => {
                        let r = if op == "allocate" {
                            bm.allocate(a as u32, b)
                        } else {
                            bm.append(a as u32, b)
                        };
                        r.to_string()
                    }
                    _ => format!("err bad args '{cmd}'"),
                },
                ("fork", 3) => match (num(1), num(2)) {
                    (Ok(a), Ok(b)) if a <= u32::MAX as usize && b <= u32::MAX as usize => {
                        bm.fork(a as u32, b as u32).to_string()
                    }
                    _ => format!("err bad args '{cmd}'"),
                },
                ("free", 2) => match num(1) {
                    Ok(a) if a <= u32::MAX as usize => {
                        bm.free(a as u32);
                        "ok".into()
                    }
                    _ => format!("err bad args '{cmd}'"),
                },
                ("translate", 3) => match (num(1), num(2)) {
                    (Ok(a), Ok(b)) if a <= u32::MAX as usize => match bm.translate(a as u32, b) {
                        Some(b) => b.to_string(),
                        None => "none".into(),
                    },
                    _ => format!("err bad args '{cmd}'"),
                },
                ("free_blocks", 1) => bm.free_blocks().to_string(),
                _ => format!("err unknown command '{cmd}'"),
            }
        }
        None => "err empty command".into(),
    }
}
