//! kv-block-manager — forge lab 02.
//!
//! PagedAttention, from the inside. You get a fixed pool of physical KV
//! blocks and must implement vLLM's block manager: per-sequence block
//! tables, `fork` with reference counting, and copy-on-write when a shared
//! tail block is appended to. This is T2 virtual memory (page tables,
//! fork(2), CoW) wearing a GPU — and the direct descendant of your lab 01
//! free-list allocator.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/manager.rs     (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.            │
//! └────────────────────────────────────────────────────────────────┘
//!
//! The model (same simplifications the vLLM paper makes):
//!   * A sequence is `len` tokens; it needs ceil(len / block_size) blocks.
//!   * `fork` shares ALL of the parent's blocks (refcount++) — beam search
//!     and parallel sampling do exactly this.
//!   * A shared block is read-only. Appending into a shared (partial) tail
//!     block triggers copy-on-write: new private block, refcount-- on the
//!     shared one.
//!   * All-or-nothing: if the pool can't satisfy an operation, return
//!     false and leave ALL state untouched. Half-applied allocations are
//!     how production engines corrupt themselves.
//!   * `free` decrements refcounts; a block returns to the pool only at 0.
//!     Leak one and check 6 (the churn gauntlet) will starve you.

mod manager;

use manager::BlockManager;
use kslab::{Check, Report};

const POOL: usize = 8; // physical blocks in the small scenarios
const BS: usize = 16; // tokens per block

/* --------------------------- determinism ---------------------------- */

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. paging: block-table math — ceil(tokens/BS) blocks, correct
///    translation, isolation between sequences.
pub fn check_paging() -> Check {
    const ID: &str = "paging";
    const LABEL: &str = "block-table math and translation";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 20) || !m.allocate(2, 16) || !m.allocate(3, 17) {
        return Check::fail(ID, LABEL, "allocate failed on an empty 8-block pool");
    }
    // 20→2 blocks, 16→1, 17→2 ⇒ 5 used, 3 free
    if m.free_blocks() != 3 {
        return Check::fail(
            ID,
            LABEL,
            format!("expected 3 free blocks after 20+16+17 tokens, got {}", m.free_blocks()),
        );
    }
    let a = m.translate(1, 0);
    let b = m.translate(1, 15);
    let c = m.translate(1, 16);
    if a.is_none() || a != b {
        return Check::fail(ID, LABEL, format!("tokens 0 and 15 must share a block, got {a:?} vs {b:?}"));
    }
    if c.is_none() || c == a {
        return Check::fail(ID, LABEL, format!("token 16 must be in the next block, got {c:?}"));
    }
    if m.translate(1, 20).is_some() {
        return Check::fail(ID, LABEL, "translate past the sequence end must be None");
    }
    // isolation: no physical block shared between seqs without fork
    for s in 1..=3u32 {
        for t in (s + 1)..=3u32 {
            for tok in 0..17usize {
                let (x, y) = (m.translate(s, tok), m.translate(t, tok));
                if x.is_some() && x == y {
                    return Check::fail(ID, LABEL, format!("seqs {s} and {t} alias a block at token {tok} without fork"));
                }
            }
        }
    }
    Check::pass(ID, LABEL, "ceil math, translation, and isolation all correct")
}

/// 2. capacity: the pool is finite — failed allocations are clean no-ops,
///    freed blocks come back.
pub fn check_capacity() -> Check {
    const ID: &str = "capacity";
    const LABEL: &str = "pool exhaustion is atomic; freed blocks return";
    let mut m = BlockManager::new(4, BS);
    if !m.allocate(1, 4 * BS) {
        return Check::fail(ID, LABEL, "could not fill an empty pool");
    }
    if m.free_blocks() != 0 {
        return Check::fail(ID, LABEL, format!("pool should be full, {} blocks free", m.free_blocks()));
    }
    if m.allocate(2, 1) {
        return Check::fail(ID, LABEL, "allocate succeeded on a full pool — blocks from nowhere");
    }
    if m.free_blocks() != 0 {
        return Check::fail(ID, LABEL, "failed allocate mutated state — must be all-or-nothing");
    }
    m.free(1);
    if m.free_blocks() != 4 {
        return Check::fail(ID, LABEL, format!("free(1) should return 4 blocks, got {}", m.free_blocks()));
    }
    if !m.allocate(2, BS) {
        return Check::fail(ID, LABEL, "allocate failed right after free — blocks were not recycled");
    }
    Check::pass(ID, LABEL, "exhaustion is clean, recycling works")
}

/// 3. fork_shares: fork copies the block TABLE, not the blocks — zero
///    allocation, identical translation.
pub fn check_fork_shares() -> Check {
    const ID: &str = "fork_shares";
    const LABEL: &str = "fork shares blocks via refcounts (zero-copy)";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 40) {
        return Check::fail(ID, LABEL, "allocate failed");
    }
    let before = m.free_blocks();
    if !m.fork(1, 2) {
        return Check::fail(ID, LABEL, "fork(1, 2) failed with free blocks available");
    }
    if m.free_blocks() != before {
        return Check::fail(
            ID,
            LABEL,
            format!("fork allocated blocks ({before} → {} free) — fork is table copy + refcount, not memcpy", m.free_blocks()),
        );
    }
    for t in 0..40usize {
        if m.translate(1, t) != m.translate(2, t) {
            return Check::fail(ID, LABEL, format!("token {t} diverged right after fork — nothing was written yet"));
        }
    }
    Check::pass(ID, LABEL, "40 tokens shared, zero blocks allocated")
}

/// 4. cow: appending to a shared partial tail copies exactly one block;
///    the parent is untouched; the shared prefix stays shared.
pub fn check_cow() -> Check {
    const ID: &str = "cow";
    const LABEL: &str = "copy-on-write on append to shared tail";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 40) || !m.fork(1, 2) {
        return Check::fail(ID, LABEL, "setup failed");
    }
    let parent_tail = m.translate(1, 39);
    let before = m.free_blocks();
    if !m.append(2, 1) {
        return Check::fail(ID, LABEL, "append(2, 1) failed with free blocks available");
    }
    if m.free_blocks() != before - 1 {
        return Check::fail(
            ID,
            LABEL,
            format!("CoW should consume exactly 1 block ({before} → {} free)", m.free_blocks()),
        );
    }
    if m.translate(1, 39) != parent_tail {
        return Check::fail(ID, LABEL, "the PARENT's tail moved during the child's append — CoW must not touch the parent");
    }
    if m.translate(2, 39) == m.translate(1, 39) {
        return Check::fail(ID, LABEL, "child still aliases the shared tail after append — no copy happened");
    }
    for t in 0..32usize {
        if m.translate(1, t) != m.translate(2, t) {
            return Check::fail(ID, LABEL, format!("prefix token {t} diverged — CoW must copy only the tail block"));
        }
    }
    Check::pass(ID, LABEL, "one block copied, prefix still shared, parent untouched")
}

/// 5. free_refcount: freeing one sharer frees nothing; freeing the last
///    sharer frees everything.
pub fn check_free_refcount() -> Check {
    const ID: &str = "free_refcount";
    const LABEL: &str = "refcounted free — shared blocks survive until the last owner";
    let mut m = BlockManager::new(POOL, BS);
    if !m.allocate(1, 40) || !m.fork(1, 2) {
        return Check::fail(ID, LABEL, "setup failed");
    }
    let before = m.free_blocks(); // 5
    m.free(1);
    if m.free_blocks() != before {
        return Check::fail(
            ID,
            LABEL,
            format!("free(1) returned blocks still shared by seq 2 ({before} → {} free)", m.free_blocks()),
        );
    }
    for t in 0..40usize {
        if m.translate(2, t).is_none() {
            return Check::fail(ID, LABEL, format!("seq 2 lost token {t} when seq 1 was freed — refcount underflow"));
        }
    }
    m.free(2);
    if m.free_blocks() != POOL {
        return Check::fail(ID, LABEL, format!("pool should be whole again ({}/{})", m.free_blocks(), POOL));
    }
    Check::pass(ID, LABEL, "blocks outlive every owner but the last")
}

/// 6. gauntlet: 2000 deterministic mixed ops at churn. The invariant that
///    must hold after EVERY op:
///      free_blocks + |distinct blocks referenced by live seqs| == POOL
///    Break refcounting anywhere (leak, double-free, aliasing) and this
///    equation breaks — a leaking manager eventually can't allocate at all.
pub fn check_gauntlet() -> Check {
    const ID: &str = "gauntlet";
    const LABEL: &str = "2000-op churn: block conservation after every op";
    const N: usize = 64;
    let mut m = BlockManager::new(N, BS);
    let mut rng = Rng(0x6A17);
    // seq slots 0..16; live[i] = Some(token_len) when alive
    let mut live: [Option<usize>; 16] = [None; 16];
    let live_ids = |live: &[Option<usize>; 16]| -> Vec<u32> {
        live.iter().enumerate().filter(|(_, l)| l.is_some()).map(|(i, _)| i as u32).collect()
    };
    let conservation = |m: &BlockManager, live: &[Option<usize>; 16]| -> Result<usize, String> {
        let mut used = [false; N];
        let mut used_n = 0usize;
        for (id, len) in live.iter().enumerate() {
            if let Some(len) = len {
                for t in 0..*len {
                    match m.translate(id as u32, t) {
                        Some(b) if b < N => {
                            if !used[b] {
                                used[b] = true;
                                used_n += 1;
                            }
                        }
                        Some(b) => return Err(format!("seq {id} token {t} → block {b} ≥ pool size {N}")),
                        None => return Err(format!("seq {id} lost token {t}")),
                    }
                }
            }
        }
        Ok(used_n)
    };

    for op in 0..2000usize {
        let action = rng.below(100);
        let ids = live_ids(&live);
        if action < 25 || ids.is_empty() {
            // allocate a fresh seq
            let Some(slot) = live.iter().position(|l| l.is_none()) else { continue };
            let tokens = 1 + rng.below(96);
            if m.allocate(slot as u32, tokens) {
                live[slot] = Some(tokens);
            }
        } else if action < 55 {
            // append
            let id = ids[rng.below(ids.len())];
            let n = 1 + rng.below(16);
            if m.append(id, n) {
                live[id as usize] = live[id as usize].map(|l| l + n);
            }
        } else if action < 70 {
            // fork into a free slot
            let id = ids[rng.below(ids.len())];
            let Some(slot) = live.iter().position(|l| l.is_none()) else { continue };
            if m.fork(id, slot as u32) {
                live[slot] = live[id as usize];
            }
        } else {
            // free
            let id = ids[rng.below(ids.len())];
            m.free(id);
            live[id as usize] = None;
        }
        match conservation(&m, &live) {
            Ok(used) => {
                if m.free_blocks() + used != N {
                    return Check::fail(
                        ID,
                        LABEL,
                        format!(
                            "op {op}: conservation broken — {} free + {used} referenced ≠ {N} total. A block leaked or was double-freed.",
                            m.free_blocks()
                        ),
                    );
                }
            }
            Err(e) => return Check::fail(ID, LABEL, format!("op {op}: {e}")),
        }
    }
    Check::pass(ID, LABEL, "2000 ops, conservation held after every single one")
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_paging(),
        check_capacity(),
        check_fork_shares(),
        check_cow(),
        check_free_refcount(),
        check_gauntlet(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "kv-block-manager", version: 1, checks: self_checks() };
    kslab::emit(&report)
}

/* --------------------------- fleet bridge --------------------------- */
/* The Fleet page (/fleet) drives YOUR manager live through this bridge:
   a line protocol over the same memory ABI. The host writes a command
   into module memory with ks_alloc, calls ks_invoke, reads the reply.

     init <num_blocks> <block_size>        → ok
     allocate <seq> <tokens>               → true | false
     append <seq> <n>                      → true | false
     fork <src> <dst>                      → true | false
     free <seq>                            → ok
     translate <seq> <token>               → <block id> | none
     free_blocks                           → <n>
     dump                                  → your dump() output, verbatim
*/

use std::cell::RefCell;

thread_local! {
    static FLEET_MANAGER: RefCell<Option<BlockManager>> = const { RefCell::new(None) };
}

#[no_mangle]
pub extern "C" fn ks_invoke(in_ptr: u32, in_len: u32) -> u64 {
    let bytes = unsafe { std::slice::from_raw_parts(in_ptr as *const u8, in_len as usize) };
    let cmd = String::from_utf8_lossy(bytes).into_owned();
    let reply = FLEET_MANAGER.with(|m| dispatch(&mut m.borrow_mut(), cmd.trim()));
    kslab::emit_str(&reply)
}

fn dispatch(m: &mut Option<BlockManager>, cmd: &str) -> String {
    let parts: Vec<&str> = cmd.split_whitespace().collect();
    let num = |i: usize| -> Result<usize, String> {
        parts
            .get(i)
            .and_then(|s| s.parse::<usize>().ok())
            .ok_or_else(|| format!("err bad number in '{cmd}'"))
    };
    match parts.first().copied() {
        Some("init") if parts.len() == 3 => match (num(1), num(2)) {
            (Ok(blocks), Ok(bs)) if blocks > 0 && bs > 0 => {
                *m = Some(BlockManager::new(blocks, bs));
                "ok".into()
            }
            _ => format!("err bad init '{cmd}'"),
        },
        Some("dump") if parts.len() == 1 => match m.as_ref() {
            Some(bm) => bm.dump(),
            None => "err not initialized".into(),
        },
        Some(op) => {
            let Some(bm) = m.as_mut() else { return "err not initialized".into() };
            match (op, parts.len()) {
                ("allocate", 3) | ("append", 3) => match (num(1), num(2)) {
                    (Ok(a), Ok(b)) if a <= u32::MAX as usize => {
                        let r = if op == "allocate" { bm.allocate(a as u32, b) } else { bm.append(a as u32, b) };
                        r.to_string()
                    }
                    _ => format!("err bad args '{cmd}'"),
                },
                ("fork", 3) => match (num(1), num(2)) {
                    (Ok(a), Ok(b)) if a <= u32::MAX as usize && b <= u32::MAX as usize => {
                        bm.fork(a as u32, b as u32).to_string()
                    }
                    _ => format!("err bad args '{cmd}'"),
                },
                ("free", 2) => match num(1) {
                    Ok(a) if a <= u32::MAX as usize => {
                        bm.free(a as u32);
                        "ok".into()
                    }
                    _ => format!("err bad args '{cmd}'"),
                },
                ("translate", 3) => match (num(1), num(2)) {
                    (Ok(a), Ok(b)) if a <= u32::MAX as usize => match bm.translate(a as u32, b) {
                        Some(b) => b.to_string(),
                        None => "none".into(),
                    },
                    _ => format!("err bad args '{cmd}'"),
                },
                ("free_blocks", 1) => bm.free_blocks().to_string(),
                _ => format!("err unknown command '{cmd}'"),
            }
        }
        None => "err empty command".into(),
    }
}
