//! bpe-tokenizer — forge lab 03.
//!
//! The front door of every request. Before anything is a tensor it is
//! bytes, and the tokenizer decides which ids those bytes become — the ids
//! are the model's contract, and a wrong merge order is a silent,
//! production-grade bug (the model still talks; it just gets dumber).
//! This is T5.L2 with your hands on the metal.
//!
//! ┌─────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/tokenizer.rs   (the only file with TODO(you))  │
//! │  DO NOT EDIT this file — it is the grading harness.             │
//! └─────────────────────────────────────────────────────────────────┘
//!
//! The model: byte-level BPE, GPT-2 style.
//!   * Base vocab: ids 0..=255 are the raw bytes themselves.
//!   * A merge table: ordered (left, right) → new_id rules; position in
//!     the table IS the rank (earlier = higher priority). New ids start
//!     at 256 and may themselves be merged again.
//!   * encode: start from byte ids; repeatedly find the LOWEST-RANK
//!     adjacent pair present anywhere in the sequence and replace all
//!     occurrences, left to right, non-overlapping. Stop when no pair
//!     has a rule.
//!   * decode: expand ids back to bytes (merge ids expand to their
//!     children, recursively), then UTF-8. Unknown ids decode to U+FFFD
//!     — a tokenizer must never kill the server on bad input.

pub mod tokenizer;

pub use tokenizer::Tokenizer;
use kslab::{Check, Report};

/* --------------------- a trainer, for realism ---------------------- */
/* Checks 4 and 6 use a table TRAINED on this corpus — the same 15-line
   algorithm as the lesson's Python, kept here so the table is
   deterministic and self-consistent (later merges may reference earlier
   merge ids). You do not implement training in this lab — only the
   application side, which is what serving engines actually run. */

pub const CORPUS: &str = "the scheduler schedules the batch. the batcher batches tokens. \
tokens in, tokens out. the cache caches blocks of keys and values. keys and values, \
keys and values. decode decodes the decode loop. the loop loops until the end token. \
the end token ends the stream. the stream streams tokens to the user. the user waits \
for the first token. the first token is the slowest token. the scheduler knows why.";

/// Deterministic pair-frequency trainer (ties broken by pair value).
pub fn train_bpe(corpus: &str, num_merges: usize) -> Vec<(u32, u32, u32)> {
    let mut ids: Vec<u32> = corpus.bytes().map(u32::from).collect();
    let mut merges = Vec::new();
    for i in 0..num_merges {
        let mut counts: std::collections::HashMap<(u32, u32), usize> = Default::default();
        for w in ids.windows(2) {
            *counts.entry((w[0], w[1])).or_default() += 1;
        }
        let mut ranked: Vec<((u32, u32), usize)> = counts.into_iter().collect();
        ranked.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
        let Some(&(pair, _)) = ranked.first() else { break };
        let new_id = 256 + i as u32;
        merges.push((pair.0, pair.1, new_id));
        let mut out = Vec::with_capacity(ids.len());
        let mut j = 0;
        while j < ids.len() {
            if j + 1 < ids.len() && (ids[j], ids[j + 1]) == pair {
                out.push(new_id);
                j += 2;
            } else {
                out.push(ids[j]);
                j += 1;
            }
        }
        ids = out;
    }
    merges
}

/* ------------------------------ checks ------------------------------ */

/// 1. bytes_are_ids: with no merges, encode is the identity over bytes.
pub fn check_bytes_are_ids() -> Check {
    const ID: &str = "bytes_are_ids";
    const LABEL: &str = "base vocab: byte b ↔ id b";
    let tk = Tokenizer::new(vec![]);
    let ids = tk.encode("hello");
    let want: Vec<u32> = b"hello".iter().map(|&b| u32::from(b)).collect();
    if ids != want {
        return Check::fail(ID, LABEL, format!("encode(\"hello\") = {ids:?}, want {want:?}"));
    }
    if tk.decode(&ids) != "hello" {
        return Check::fail(ID, LABEL, "decode did not invert the identity encoding");
    }
    Check::pass(ID, LABEL, "empty table → identity over bytes")
}

/// 2. merge_priority: LOWEST RANK wins, not leftmost pair. A left-greedy
///    implementation fails this.
pub fn check_merge_priority() -> Check {
    const ID: &str = "merge_priority";
    const LABEL: &str = "lowest-rank pair merges first (not leftmost)";
    // rank 0: (b,c)→256 · rank 1: (a,b)→257
    let tk = Tokenizer::new(vec![(98, 99, 256), (97, 98, 257)]);
    let ids = tk.encode("abc");
    // correct BPE: merge (b,c) first → [97, 256]; left-greedy gives [257, 99]
    if ids != vec![97, 256] {
        return Check::fail(
            ID,
            LABEL,
            format!("encode(\"abc\") = {ids:?}, want [97, 256] — rank decides, not position"),
        );
    }
    Check::pass(ID, LABEL, "rank beats position")
}

/// 3. leftmost_nonoverlap: repeated pairs merge left-to-right,
///    non-overlapping.
pub fn check_leftmost_nonoverlap() -> Check {
    const ID: &str = "leftmost_nonoverlap";
    const LABEL: &str = "repeated pairs merge left-to-right, non-overlapping";
    let tk = Tokenizer::new(vec![(97, 97, 256)]);
    let cases: [(&str, Vec<u32>); 3] = [
        ("aaaa", vec![256, 256]),
        ("aaa", vec![256, 97]),
        ("aa", vec![256]),
    ];
    for (s, want) in cases {
        let got = tk.encode(s);
        if got != want {
            return Check::fail(ID, LABEL, format!("encode({s:?}) = {got:?}, want {want:?}"));
        }
    }
    Check::pass(ID, LABEL, "aa-runs merge cleanly")
}

/// 4. roundtrip: decode(encode(x)) == x over multi-byte UTF-8 — the
///    property that makes byte-level BPE the production default.
pub fn check_roundtrip() -> Check {
    const ID: &str = "roundtrip";
    const LABEL: &str = "decode∘encode is identity over UTF-8";
    let tk = Tokenizer::new(train_bpe(CORPUS, 48));
    let corpus = [
        "the scheduler schedules the batch.",
        "hello world, hello world, hello",
        "emoji: 🦀🚀 and cjk: 推し活 and accents: naïve café",
        "— em-dash, “quotes”, and a newline\ninside",
    ];
    for s in corpus {
        let back = tk.decode(&tk.encode(s));
        if back != s {
            return Check::fail(ID, LABEL, format!("roundtrip failed for {s:?}: got {back:?}"));
        }
    }
    Check::pass(ID, LABEL, "byte-perfect over emoji, CJK, accents, punctuation")
}

/// 5. robust_decode: garbage in, replacement char out — never a panic.
pub fn check_robust_decode() -> Check {
    const ID: &str = "robust_decode";
    const LABEL: &str = "unknown ids decode to U+FFFD, empty stays empty";
    let tk = Tokenizer::new(vec![(97, 98, 256)]);
    if tk.decode(&[]) != "" {
        return Check::fail(ID, LABEL, "decode([]) must be the empty string");
    }
    let s = tk.decode(&[9999]);
    if s != "\u{FFFD}" {
        return Check::fail(ID, LABEL, format!("decode([9999]) = {s:?}, want \"\\u{{FFFD}}\""));
    }
    // a valid merge id still expands inside an otherwise-bogus sequence
    let s = tk.decode(&[256, 9999, 97]);
    if s != "ab\u{FFFD}a" {
        return Check::fail(ID, LABEL, format!("decode([256, 9999, 97]) = {s:?}, want \"ab\\u{{FFFD}}a\""));
    }
    Check::pass(ID, LABEL, "bad ids degrade, never crash")
}

/// 6. contract: a trained table applied to unseen text must produce the
///    EXACT reference ids. The ids are the model's contract — "close"
///    does not exist.
pub fn check_contract() -> Check {
    const ID: &str = "contract";
    const LABEL: &str = "exact ids on unseen text (the model's contract)";
    const TEXT: &str = "the user waits for the first token while the scheduler batches the stream";
    const EXPECTED: &[u32] = &EXPECTED_IDS;
    let tk = Tokenizer::new(train_bpe(CORPUS, 48));
    let ids = tk.encode(TEXT);
    if ids != EXPECTED {
        let diff = ids
            .iter()
            .zip(EXPECTED.iter())
            .position(|(a, b)| a != b)
            .map(|i| format!("first diff at index {i}"))
            .unwrap_or_else(|| format!("length {} ≠ {}", ids.len(), EXPECTED.len()));
        return Check::fail(ID, LABEL, format!("encode produced wrong ids ({diff})"));
    }
    Check::pass(ID, LABEL, format!("{} tokens, bit-exact vs reference", ids.len()))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_bytes_are_ids(),
        check_merge_priority(),
        check_leftmost_nonoverlap(),
        check_roundtrip(),
        check_robust_decode(),
        check_contract(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "bpe-tokenizer", version: 1, checks: self_checks() };
    kslab::emit(&report)
}

/// Reference ids for check_contract — computed from the reference
/// implementation over the trained table. (Placeholder until embedded.)
const EXPECTED_IDS: &[u32] = &[
    116, 258, 117, 115, 271, 32, 119, 97, 105, 116, 261, 102, 111, 114, 259, 102, 105, 114,
    268, 264, 32, 119, 104, 105, 108, 101, 259, 299, 271, 32, 278, 266, 286, 293,
];
