//! bpe-tokenizer — forge lab 03.
//!
//! The front door of every request. Before anything is a tensor it is
//! bytes, and the tokenizer decides which ids those bytes become — the ids
//! are the model's contract, and a wrong merge order is a silent,
//! production-grade bug (the model still talks; it just gets dumber).
//! This is T5.L2 with your hands on the metal.
//!
//! ┌─────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/tokenizer.rs   (the only file with TODO(you))  │
//! │  DO NOT EDIT this file — it is the grading harness.             │
//! └─────────────────────────────────────────────────────────────────┘
//!
//! The model: byte-level BPE, GPT-2 style.
//!   * Base vocab: ids 0..=255 are the raw bytes themselves.
//!   * A merge table: ordered (left, right) → new_id rules; position in
//!     the table IS the rank (earlier = higher priority). New ids start
//!     at 256 and may themselves be merged again.
//!   * encode: start from byte ids; repeatedly find the LOWEST-RANK
//!     adjacent pair present anywhere in the sequence and replace all
//!     occurrences, left to right, non-overlapping. Stop when no pair
//!     has a rule.
//!   * decode: expand ids back to bytes (merge ids expand to their
//!     children, recursively), then UTF-8. Unknown ids decode to U+FFFD
//!     — a tokenizer must never kill the server on bad input.
//!
//! The checks below are the single source of truth:
//!   * `cargo test` runs them on your machine, on their default seeds and on
//!     32 extra seeds.
//!   * `cargo build --release --target wasm32-unknown-unknown` bakes them
//!     into the .wasm you drop into kernelspace → the site runs each check on
//!     its own (template v2), with fresh seeds for the two seeded ones, and
//!     renders exactly these results.
//!
//! A `todo!()` in your code traps that check; the site shows it as "not
//! implemented yet" with the panic text, and the other checks still run.
//!
//! Which check catches which mistake:
//!
//! ```text
//!   bytes_are_ids         a base vocabulary that is not "byte b is id b"
//!   merge_priority        merging the leftmost pair instead of the lowest rank
//!   leftmost_nonoverlap   a run `aaa` merged right-to-left or overlapping
//!   roundtrip             a decode that loses a byte, or stops expanding a
//!                         merge id after one level: a seeded table (16–48
//!                         merges) and seeded UTF-8 text
//!   robust_decode         an unknown id that panics or vanishes
//!   contract              the wrong ids on a fixed unseen text, or an encode
//!                         that stops while a merge rule still applies (the
//!                         seeded part: six fresh texts must be fully merged)
//! ```

pub mod tokenizer;

pub use tokenizer::Tokenizer;
use kslab::{Check, CheckDef, Ctx, Lab, Rng};

#[cfg(not(feature = "reference"))]
const LAB_ID: &str = "bpe-tokenizer";
/// A `--features reference` build names itself, and earns no credit anywhere.
#[cfg(feature = "reference")]
const LAB_ID: &str = "bpe-tokenizer@reference";

/// The checks, in grading order. Ids and labels match `src/data/labs.ts`.
pub static CHECKS: [CheckDef; 6] = [
    CheckDef { id: "bytes_are_ids", label: BYTES_ARE_IDS, stage: 1, seeded: false, default_seed: 0, run: check_bytes_are_ids },
    CheckDef { id: "merge_priority", label: MERGE_PRIORITY, stage: 2, seeded: false, default_seed: 0, run: check_merge_priority },
    CheckDef { id: "leftmost_nonoverlap", label: LEFTMOST_NONOVERLAP, stage: 2, seeded: false, default_seed: 0, run: check_leftmost_nonoverlap },
    CheckDef { id: "roundtrip", label: ROUNDTRIP, stage: 3, seeded: true, default_seed: 0x0B9E, run: check_roundtrip },
    CheckDef { id: "robust_decode", label: ROBUST_DECODE, stage: 3, seeded: false, default_seed: 0, run: check_robust_decode },
    CheckDef { id: "contract", label: CONTRACT, stage: 4, seeded: true, default_seed: 0xC0DE, run: check_contract },
];

pub static LAB: Lab = Lab { id: LAB_ID, version: 2, checks: &CHECKS };

const BYTES_ARE_IDS: &str = "base vocab: byte b ↔ id b";
const MERGE_PRIORITY: &str = "lowest-rank pair merges first (not leftmost)";
const LEFTMOST_NONOVERLAP: &str = "repeated pairs merge left-to-right, non-overlapping";
const ROUNDTRIP: &str = "decode∘encode is identity over UTF-8";
const ROBUST_DECODE: &str = "unknown ids decode to U+FFFD, empty stays empty";
const CONTRACT: &str = "exact ids on unseen text (the model’s contract)";

/* --------------------- a trainer, for realism ---------------------- */
/* Checks 4 and 6 use a table TRAINED on this corpus — the same 15-line
   algorithm as the lesson's Python, kept here so the table is
   deterministic and self-consistent (later merges may reference earlier
   merge ids). You do not implement training in this lab — only the
   application side, which is what serving engines actually run. */

pub const CORPUS: &str = "the scheduler schedules the batch. the batcher batches tokens. \
tokens in, tokens out. the cache caches blocks of keys and values. keys and values, \
keys and values. decode decodes the decode loop. the loop loops until the end token. \
the end token ends the stream. the stream streams tokens to the user. the user waits \
for the first token. the first token is the slowest token. the scheduler knows why.";

/// Deterministic pair-frequency trainer (ties broken by pair value).
pub fn train_bpe(corpus: &str, num_merges: usize) -> Vec<(u32, u32, u32)> {
    let mut ids: Vec<u32> = corpus.bytes().map(u32::from).collect();
    let mut merges = Vec::new();
    for i in 0..num_merges {
        let mut counts: std::collections::HashMap<(u32, u32), usize> = Default::default();
        for w in ids.windows(2) {
            *counts.entry((w[0], w[1])).or_default() += 1;
        }
        let mut ranked: Vec<((u32, u32), usize)> = counts.into_iter().collect();
        ranked.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
        let Some(&(pair, _)) = ranked.first() else { break };
        let new_id = 256 + i as u32;
        merges.push((pair.0, pair.1, new_id));
        let mut out = Vec::with_capacity(ids.len());
        let mut j = 0;
        while j < ids.len() {
            if j + 1 < ids.len() && (ids[j], ids[j + 1]) == pair {
                out.push(new_id);
                j += 2;
            } else {
                out.push(ids[j]);
                j += 1;
            }
        }
        ids = out;
    }
    merges
}

/* ------------------------------ checks ------------------------------ */

/// 1. bytes_are_ids: with no merges, encode is the identity over bytes.
pub fn check_bytes_are_ids(_: &Ctx) -> Check {
    const ID: &str = "bytes_are_ids";
    let tk = Tokenizer::new(vec![]);
    let ids = tk.encode("hello");
    let want: Vec<u32> = b"hello".iter().map(|&b| u32::from(b)).collect();
    if ids != want {
        return Check::fail(ID, BYTES_ARE_IDS, format!("encode(\"hello\") = {ids:?}, want {want:?}"));
    }
    if tk.decode(&ids) != "hello" {
        return Check::fail(ID, BYTES_ARE_IDS, "decode did not invert the identity encoding");
    }
    Check::pass(ID, BYTES_ARE_IDS, "empty table → identity over bytes")
}

/// 2. merge_priority: LOWEST RANK wins, not leftmost pair. A left-greedy
///    implementation fails this.
pub fn check_merge_priority(_: &Ctx) -> Check {
    const ID: &str = "merge_priority";
    // rank 0: (b,c)→256 · rank 1: (a,b)→257
    let tk = Tokenizer::new(vec![(98, 99, 256), (97, 98, 257)]);
    let ids = tk.encode("abc");
    // correct BPE: merge (b,c) first → [97, 256]; left-greedy gives [257, 99]
    if ids != vec![97, 256] {
        return Check::fail(
            ID,
            MERGE_PRIORITY,
            format!("encode(\"abc\") = {ids:?}, want [97, 256] — rank decides, not position"),
        );
    }
    Check::pass(ID, MERGE_PRIORITY, "rank beats position")
}

/// 3. leftmost_nonoverlap: repeated pairs merge left-to-right,
///    non-overlapping.
pub fn check_leftmost_nonoverlap(_: &Ctx) -> Check {
    const ID: &str = "leftmost_nonoverlap";
    let tk = Tokenizer::new(vec![(97, 97, 256)]);
    let cases: [(&str, Vec<u32>); 3] = [
        ("aaaa", vec![256, 256]),
        ("aaa", vec![256, 97]),
        ("aa", vec![256]),
    ];
    for (s, want) in cases {
        let got = tk.encode(s);
        if got != want {
            return Check::fail(ID, LEFTMOST_NONOVERLAP, format!("encode({s:?}) = {got:?}, want {want:?}"));
        }
    }
    Check::pass(ID, LEFTMOST_NONOVERLAP, "aa-runs merge cleanly")
}

/// Text for the seeded checks: words from the training corpus, chunks it never
/// saw (emoji, CJK, accents, quotes, a newline) and single scalars from a few
/// Unicode blocks, so every table sees both merged and raw multi-byte runs.
fn seeded_text(rng: &mut Rng, pieces: usize) -> String {
    const WORDS: [&str; 14] = [
        "the", "scheduler", "batch", "tokens", "keys", "values", "decode", "loop", "stream", "user", "first", "token",
        "cache", "blocks",
    ];
    const CHUNKS: [&str; 9] = ["🦀", "推し活", "naïve", "café", "—", "“quoted”", "\n", "日本語", "ß"];
    const BLOCKS: [(usize, usize); 5] = [(0x20, 0x7E), (0xA1, 0xFF), (0x400, 0x4FF), (0x4E00, 0x9FFF), (0x1F300, 0x1F64F)];
    let mut s = String::new();
    for _ in 0..pieces {
        match rng.below(10) {
            0..=5 => s.push_str(WORDS[rng.below(WORDS.len())]),
            6 | 7 => s.push_str(CHUNKS[rng.below(CHUNKS.len())]),
            _ => {
                let (lo, hi) = BLOCKS[rng.below(BLOCKS.len())];
                s.push(char::from_u32(rng.range(lo, hi) as u32).unwrap_or('?'));
            }
        }
        if rng.below(4) != 0 {
            s.push(' ');
        }
    }
    s
}

/// 4. roundtrip: decode(encode(x)) == x over multi-byte UTF-8 — the
///    property that makes byte-level BPE the production default. The table
///    (16–48 merges) and eight of the twelve texts come from the seed.
pub fn check_roundtrip(ctx: &Ctx) -> Check {
    const ID: &str = "roundtrip";
    let mut rng = Rng::seeded(ctx.seed);
    let merges = 16 + rng.below(33);
    let tk = Tokenizer::new(train_bpe(CORPUS, merges));
    let mut texts: Vec<String> = [
        "the scheduler schedules the batch.",
        "hello world, hello world, hello",
        "emoji: 🦀🚀 and cjk: 推し活 and accents: naïve café",
        "— em-dash, “quotes”, and a newline\ninside",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect();
    for _ in 0..8 {
        let pieces = 4 + rng.below(21);
        texts.push(seeded_text(&mut rng, pieces));
    }
    for s in &texts {
        let ids = tk.encode(s);
        let back = tk.decode(&ids);
        if back != *s {
            return Check::fail(
                ID,
                ROUNDTRIP,
                format!("roundtrip failed with a {merges}-merge table for {s:?}: got {back:?}"),
            );
        }
    }
    Check::pass(ID, ROUNDTRIP, format!("byte-perfect over {} texts with a {merges}-merge table", texts.len()))
}

/// 5. robust_decode: garbage in, replacement char out — never a panic.
pub fn check_robust_decode(_: &Ctx) -> Check {
    const ID: &str = "robust_decode";
    let tk = Tokenizer::new(vec![(97, 98, 256)]);
    if tk.decode(&[]) != "" {
        return Check::fail(ID, ROBUST_DECODE, "decode([]) must be the empty string");
    }
    let s = tk.decode(&[9999]);
    if s != "\u{FFFD}" {
        return Check::fail(ID, ROBUST_DECODE, format!("decode([9999]) = {s:?}, want \"\\u{{FFFD}}\""));
    }
    // a valid merge id still expands inside an otherwise-bogus sequence
    let s = tk.decode(&[256, 9999, 97]);
    if s != "ab\u{FFFD}a" {
        return Check::fail(ID, ROBUST_DECODE, format!("decode([256, 9999, 97]) = {s:?}, want \"ab\\u{{FFFD}}a\""));
    }
    Check::pass(ID, ROBUST_DECODE, "bad ids degrade, never crash")
}

/// 6. contract: a trained table applied to unseen text must produce the
///    EXACT reference ids. The ids are the model's contract — "close"
///    does not exist. Then, on texts drawn from the seed, encode must not
///    stop while a merge rule still applies, and decode must give the text back.
pub fn check_contract(ctx: &Ctx) -> Check {
    const ID: &str = "contract";
    const TEXT: &str = "the user waits for the first token while the scheduler batches the stream";
    const EXPECTED: &[u32] = &EXPECTED_IDS;
    let merges = train_bpe(CORPUS, 48);
    let tk = Tokenizer::new(merges.clone());
    let ids = tk.encode(TEXT);
    if ids != EXPECTED {
        let diff = ids
            .iter()
            .zip(EXPECTED.iter())
            .position(|(a, b)| a != b)
            .map(|i| format!("first diff at index {i}"))
            .unwrap_or_else(|| format!("length {} ≠ {}", ids.len(), EXPECTED.len()));
        return Check::fail(ID, CONTRACT, format!("encode produced wrong ids ({diff})"));
    }
    let mut rng = Rng::seeded(ctx.seed);
    for n in 0..6 {
        let pieces = 6 + rng.below(15);
        let text = seeded_text(&mut rng, pieces);
        let ids = tk.encode(&text);
        if let Some(i) = (0..ids.len().saturating_sub(1)).find(|&i| merges.iter().any(|m| (m.0, m.1) == (ids[i], ids[i + 1]))) {
            return Check::fail(
                ID,
                CONTRACT,
                format!("text {n}: ids {} and {} at index {i} still have a merge rule — encode stopped early", ids[i], ids[i + 1]),
            );
        }
        if tk.decode(&ids) != text {
            return Check::fail(ID, CONTRACT, format!("text {n}: decode(encode(text)) is not the text"));
        }
    }
    Check::pass(ID, CONTRACT, format!("{} tokens, bit-exact vs reference; 6 fresh texts fully merged", ids.len()))
}

/// The full suite on default seeds, in grading order (v1 report order).
pub fn self_checks() -> Vec<Check> {
    CHECKS.iter().map(|c| (c.run)(&Ctx { seed: c.default_seed, fresh: false })).collect()
}

/* ------------------------------ probe ------------------------------- */

/// `probe <seed>`: your tokenizer on one seeded text under the 48-merge
/// table, summarised in one line: input bytes, ids out, how many ids are
/// merges, distinct ids, bytes per token and whether the text came back.
/// Deterministic for a given seed and tokenizer.
pub fn probe(seed: u32) -> String {
    let mut rng = Rng::seeded(seed);
    let tk = Tokenizer::new(train_bpe(CORPUS, 48));
    let pieces = 24 + rng.below(25);
    let text = seeded_text(&mut rng, pieces);
    let ids = tk.encode(&text);
    let merged = ids.iter().filter(|&&i| i >= 256).count();
    let distinct = ids.iter().collect::<std::collections::BTreeSet<_>>().len();
    let ratio = if ids.is_empty() { 0.0 } else { text.len() as f64 / ids.len() as f64 };
    let back = tk.decode(&ids) == text;
    format!(
        "bytes={} tokens={} merged={merged} distinct={distinct} ratio={ratio:.2} roundtrip={back}",
        text.len(),
        ids.len()
    )
}

/* ------------------------------ wasm ABI ---------------------------- */

kslab::export_abi_v2!();

#[no_mangle]
pub extern "C" fn ks_run(in_ptr: u32, in_len: u32) -> u64 {
    kslab::run(unsafe { kslab::input(in_ptr, in_len) }, &LAB)
}

/// The runtime bridge: `probe <seed>` (see `probe`).
#[no_mangle]
pub extern "C" fn ks_invoke(in_ptr: u32, in_len: u32) -> u64 {
    kslab::install_panic_hook();
    let cmd = std::str::from_utf8(unsafe { kslab::input(in_ptr, in_len) }).unwrap_or("");
    let mut it = cmd.split_whitespace();
    let reply = match (it.next(), it.next().map(str::parse::<u32>)) {
        (Some("probe"), Some(Ok(seed))) => probe(seed),
        _ => format!("err unknown command {:?} (try: probe <seed>)", kslab::clip(cmd.trim(), 40)),
    };
    kslab::emit_str(&reply)
}

/// Reference ids for check_contract — computed from the reference
/// implementation over the trained table. (Placeholder until embedded.)
const EXPECTED_IDS: &[u32] = &[
    116, 258, 117, 115, 271, 32, 119, 97, 105, 116, 261, 102, 111, 114, 259, 102, 105, 114,
    268, 264, 32, 119, 104, 105, 108, 101, 259, 299, 271, 32, 278, 266, 286, 293,
];
