//! toy-executor — forge lab 05.
//!
//! Async, demystified by construction. The unsafe RawWaker vtable is
//! provided below (it's plumbing that can't fail interestingly); YOU build
//! the parts that are actually the lesson: the task queue, spawn, the
//! take/poll/restore loop, and block_on. After this lab, tokio is an
//! engineering detail, not magic. T3.L5's code, running for real.
//!
//! ┌─────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/executor.rs    (the only file with TODO(you))  │
//! │  DO NOT EDIT this file — it is the grading harness AND the      │
//! │  waker plumbing.                                                │
//! └─────────────────────────────────────────────────────────────────┘
//!
//! The reactor contract the checks enforce:
//!   * A task that returns Pending without waking itself is NEVER
//!     re-polled. Wakeups are the only re-scheduling mechanism.
//!   * Woken tasks run in FIFO wake order.
//!   * A Ready task is dropped, never re-polled (a stale wake after
//!     completion pops a task whose future is gone — skip it).
//!   * spawn must work from INSIDE a poll (tasks spawning tasks).

mod executor;

pub use executor::{block_on, Executor};
use kslab::{Check, Report};

use std::cell::{Cell, RefCell};
use std::collections::VecDeque;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;
use std::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

/* ------------------------ waker plumbing (given) -------------------- */

/// The executor's run queue. Single-threaded: Rc + RefCell, because a toy
/// executor's job is to teach the state machine, not the contention.
pub struct TaskQueue {
    pub inner: RefCell<VecDeque<Rc<Task>>>,
}

impl TaskQueue {
    pub fn new() -> Rc<Self> {
        Rc::new(TaskQueue { inner: RefCell::new(VecDeque::new()) })
    }
}

/// One spawned future. `future` is None after completion — the executor
/// takes it out to poll and only puts it back on Pending.
pub struct Task {
    pub future: RefCell<Option<Pin<Box<dyn Future<Output = ()>>>>>,
    pub queue: Rc<TaskQueue>,
}

impl Task {
    /// Re-queue this task. This is what every Waker ultimately does.
    pub fn wake_task(self: &Rc<Task>) {
        self.queue.inner.borrow_mut().push_back(Rc::clone(self));
    }
}

/* RawWaker over Rc<Task>: clone/wake/wake_by_ref/drop. This is the unsafe
   you would write once and never touch again — provided so the lab grades
   scheduling, not vtable plumbing. */

fn raw_waker(task: &Rc<Task>) -> RawWaker {
    RawWaker::new(Rc::into_raw(Rc::clone(task)) as *const (), &VTABLE)
}

static VTABLE: RawWakerVTable = RawWakerVTable::new(waker_clone, waker_wake, waker_wake_ref, waker_drop);

unsafe fn waker_clone(data: *const ()) -> RawWaker {
    let rc = Rc::<Task>::from_raw(data as *const Task);
    let rc2 = Rc::clone(&rc);
    let _ = Rc::into_raw(rc); // keep the original strong ref
    RawWaker::new(Rc::into_raw(rc2) as *const (), &VTABLE)
}

unsafe fn waker_wake(data: *const ()) {
    let rc = Rc::<Task>::from_raw(data as *const Task);
    rc.wake_task(); // consumes the strong ref
}

unsafe fn waker_wake_ref(data: *const ()) {
    let rc = std::mem::ManuallyDrop::new(Rc::<Task>::from_raw(data as *const Task));
    rc.wake_task();
}

unsafe fn waker_drop(data: *const ()) {
    drop(Rc::<Task>::from_raw(data as *const Task));
}

/// Build a Waker that re-queues `task` on wake.
pub fn make_waker(task: &Rc<Task>) -> Waker {
    unsafe { Waker::from_raw(raw_waker(task)) }
}

/* --------------------------- test futures --------------------------- */

/// Pends `n` times (waking itself each time), then completes.
/// Counts its own polls.
struct YieldN {
    remaining: u32,
    polls: Rc<Cell<u32>>,
    on_ready: Option<Rc<Cell<u32>>>,
}

impl Future for YieldN {
    type Output = ();
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
        let this = self.get_mut();
        this.polls.set(this.polls.get() + 1);
        if this.remaining == 0 {
            if let Some(c) = &this.on_ready {
                c.set(c.get() + 1);
            }
            Poll::Ready(())
        } else {
            this.remaining -= 1;
            cx.waker().wake_by_ref();
            Poll::Pending
        }
    }
}

/// Two tasks alternate turns 100 times via shared state — the
/// store-the-other-guy's-waker pattern every reactor uses.
struct PingPong {
    count: u32,
    target: u32,
    turn: usize,
    wakers: [Option<Waker>; 2],
    done: [bool; 2],
}

struct PingPongTask {
    id: usize,
    shared: Rc<RefCell<PingPong>>,
}

impl Future for PingPongTask {
    type Output = ();
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
        let mut s = self.shared.borrow_mut();
        if s.count >= s.target {
            s.done[self.id] = true;
            if let Some(w) = s.wakers[1 - self.id].take() {
                w.wake_by_ref();
            }
            return Poll::Ready(());
        }
        if s.turn == self.id {
            s.count += 1;
            s.turn = 1 - self.id;
            s.wakers[self.id] = Some(cx.waker().clone());
            match s.wakers[1 - self.id].take() {
                Some(w) => w.wake_by_ref(),
                None => cx.waker().wake_by_ref(), // other side hasn't polled yet — try again
            }
            Poll::Pending
        } else {
            s.wakers[self.id] = Some(cx.waker().clone());
            Poll::Pending
        }
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. block_on: drives a future to completion, yields included.
pub fn check_block_on() -> Check {
    const ID: &str = "block_on";
    const LABEL: &str = "block_on returns values, through yields";
    let plain = block_on(async { 42 });
    if plain != 42 {
        return Check::fail(ID, LABEL, format!("block_on(async {{ 42 }}) = {plain}"));
    }
    let yielded = block_on(async {
        let polls = Rc::new(Cell::new(0u32));
        YieldN { remaining: 1, polls: Rc::clone(&polls), on_ready: None }.await;
        7
    });
    if yielded != 7 {
        return Check::fail(ID, LABEL, "block_on lost the plot after a Pending — did you re-poll after wake?");
    }
    Check::pass(ID, LABEL, "immediate and self-waking futures both complete")
}

/// 2. fifo_poll: three self-yielding tasks poll in spawn order, then in
///    FIFO wake order. A stack (LIFO) fails this.
pub fn check_fifo_poll() -> Check {
    const ID: &str = "fifo_poll";
    const LABEL: &str = "spawn order, then FIFO wake order";
    let log = Rc::new(RefCell::new(Vec::new()));
    let ex = Executor::new();
    for id in 1..=3u32 {
        let log = Rc::clone(&log);
        ex.spawn(async move {
            log.borrow_mut().push(id); // first poll
            let polls = Rc::new(Cell::new(0u32));
            YieldN { remaining: 1, polls, on_ready: None }.await;
            log.borrow_mut().push(id); // second poll
        });
    }
    ex.run();
    let got = log.borrow().clone();
    let want = vec![1, 2, 3, 1, 2, 3];
    if got != want {
        return Check::fail(ID, LABEL, format!("poll order {got:?}, want {want:?} — wakeups must be FIFO"));
    }
    Check::pass(ID, LABEL, "spawn [1,2,3], wake [1,2,3]")
}

/// 3. pending_repoll: a 3-yield future is polled EXACTLY 4 times — no
///    lost wakes, no busy-spinning.
pub fn check_pending_repoll() -> Check {
    const ID: &str = "pending_repoll";
    const LABEL: &str = "Pending tasks re-polled only via wake (exactly 4 polls)";
    let ex = Executor::new();
    let polls = Rc::new(Cell::new(0u32));
    let done = Rc::new(Cell::new(0u32));
    ex.spawn(YieldN { remaining: 3, polls: Rc::clone(&polls), on_ready: Some(Rc::clone(&done)) });
    ex.run();
    if done.get() != 1 {
        return Check::fail(ID, LABEL, "task never completed — a wake was dropped");
    }
    if polls.get() != 4 {
        return Check::fail(
            ID,
            LABEL,
            format!("polled {} times, want exactly 4 — re-polling without a wake is a busy loop", polls.get()),
        );
    }
    Check::pass(ID, LABEL, "3 Pending + 1 Ready, zero wasted polls")
}

/// 4. ping_pong: two tasks wake each other 100 times through stored
///    wakers. Both must observe completion.
pub fn check_ping_pong() -> Check {
    const ID: &str = "ping_pong";
    const LABEL: &str = "cross-task wakeup ×100 via stored wakers";
    let ex = Executor::new();
    let shared = Rc::new(RefCell::new(PingPong {
        count: 0,
        target: 100,
        turn: 0,
        wakers: [None, None],
        done: [false, false],
    }));
    ex.spawn(PingPongTask { id: 0, shared: Rc::clone(&shared) });
    ex.spawn(PingPongTask { id: 1, shared: Rc::clone(&shared) });
    ex.run();
    let s = shared.borrow();
    if s.count != 100 || !s.done[0] || !s.done[1] {
        return Check::fail(
            ID,
            LABEL,
            format!("count={}, done={:?} — a wakeup was lost between tasks", s.count, s.done),
        );
    }
    Check::pass(ID, LABEL, "100 exchanges, both tasks observed completion")
}

/// 5. many_tasks: 1000 two-yield tasks → exactly 3000 polls, all complete.
pub fn check_many_tasks() -> Check {
    const ID: &str = "many_tasks";
    const LABEL: &str = "1000 tasks: exactly 3000 polls, zero lost";
    let ex = Executor::new();
    let done = Rc::new(Cell::new(0u32));
    for _ in 0..1000 {
        ex.spawn(YieldN {
            remaining: 2,
            polls: Rc::new(Cell::new(0)),
            on_ready: Some(Rc::clone(&done)),
        });
    }
    let polls = ex.run();
    if done.get() != 1000 {
        return Check::fail(ID, LABEL, format!("{} of 1000 tasks completed — tasks are being lost", done.get()));
    }
    if polls != 3000 {
        return Check::fail(ID, LABEL, format!("run() executed {polls} polls, want 3000 — double-polling or spin-waste"));
    }
    Check::pass(ID, LABEL, "1000 tasks, 3000 polls, all home")
}

/// 6. nested_spawn: spawn from inside a poll. Executors that borrow the
///    queue across poll, or snapshot it, fail (panic or lost children).
pub fn check_nested_spawn() -> Check {
    const ID: &str = "nested_spawn";
    const LABEL: &str = "tasks spawning tasks mid-run";
    let ex = Rc::new(Executor::new());
    let spawned = Rc::new(Cell::new(0u32));
    let ex2 = Rc::clone(&ex);
    let spawned2 = Rc::clone(&spawned);
    ex.spawn(async move {
        for _ in 0..5 {
            let s = Rc::clone(&spawned2);
            ex2.spawn(async move {
                s.set(s.get() + 1);
            });
        }
    });
    ex.run();
    if spawned.get() != 5 {
        return Check::fail(
            ID,
            LABEL,
            format!("{} of 5 children ran — spawn inside poll must grow the live queue", spawned.get()),
        );
    }
    Check::pass(ID, LABEL, "parent spawned 5 children mid-poll; all 5 ran")
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_block_on(),
        check_fifo_poll(),
        check_pending_repoll(),
        check_ping_pong(),
        check_many_tasks(),
        check_nested_spawn(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "toy-executor", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
