/** Verify committed trace contracts and the Rust tables generated from them. */
import { parseTraceArtifact, type TraceArtifact, type TraceRequest } from '../src/lib/traces'

const ROOT = new URL('../', import.meta.url)
const paths = {
  kimi: new URL('public/traces/kimi-conversation.json', ROOT),
  burst: new URL('public/traces/burstgpt-v2-busiest-hour.json', ROOT),
  lmsys: new URL('public/traces/lmsys-chat-1m-published-shape.json', ROOT),
  rust: new URL('labs/batching-scheduler/src/trace_scenarios.rs', ROOT),
}

async function artifact(url: URL): Promise<TraceArtifact> {
  const raw = await Bun.file(url).json()
  const parsed = await parseTraceArtifact(raw)
  for (const [index, row] of parsed.requests.entries()) {
    const keys = Object.keys(row).sort().join(',')
    if (keys !== 'o,p,t') throw new Error(`${parsed.id} row ${index} exposes fields beyond t/p/o`)
  }
  return parsed
}

function mean(rows: TraceRequest[], key: 'p' | 'o'): number {
  return rows.reduce((sum, row) => sum + row[key], 0) / rows.length
}

function rustRows(name: string, rows: TraceRequest[]): string {
  return `pub const ${name}: &[(u32, u32, u32)] = &[\n${rows
    .map((row) => `    (${row.t}, ${row.p}, ${row.o}),\n`)
    .join('')}];\n`
}

const [kimi, burst, lmsys] = await Promise.all([
  artifact(paths.kimi),
  artifact(paths.burst),
  artifact(paths.lmsys),
])

if (kimi.kind !== 'recorded' || kimi.requestCount !== 1200) throw new Error('Kimi contract drifted')
if (burst.kind !== 'recorded' || burst.requestCount !== 480 || burst.license !== 'CC-BY-4.0') {
  throw new Error('BurstGPT contract drifted')
}
if (lmsys.kind !== 'synthetic-profile' || lmsys.requestCount !== 360) {
  throw new Error('LMSYS profile must remain synthetic and contain 360 rows')
}
if (mean(lmsys.requests, 'p') !== 69.5 || mean(lmsys.requests, 'o') !== 214.5) {
  throw new Error('LMSYS published aggregate means drifted')
}

const expectedRust =
  '//! Generated by scripts/build-traces.py; do not edit by hand.\n' +
  '//! These tables mirror public/traces exactly.\n\n' +
  rustRows('BURSTGPT_REQUESTS', burst.requests) +
  '\n' +
  rustRows('LMSYS_SHAPE_REQUESTS', lmsys.requests)
const actualRust = await Bun.file(paths.rust).text()
if (actualRust !== expectedRust) throw new Error('Rust trace tables do not match the public artifacts')

for (const item of [kimi, burst, lmsys]) {
  console.log(
    `${item.id.padEnd(39)} ${String(item.requestCount).padStart(4)} rows · ` +
      `p̄ ${mean(item.requests, 'p').toFixed(1).padStart(6)} · ` +
      `ō ${mean(item.requests, 'o').toFixed(1).padStart(6)} · ${item.kind}`,
  )
}
console.log('OK: provenance schema, checksums, privacy surface, and Rust tables verified')
